const VERSION = '2026.07.23-05';
const KEY = 'orangemania-blog-editor-v1', VIEW_KEY = 'orangemania-blog-editor-view-v1', CURRENT_KEY = 'orangemania-blog-editor-current-v1', DELETED_KEY = 'orangemania-blog-editor-deleted-v1', SCHEMA_VERSION = 1;
const config = window.BLOG_EDITOR_FIREBASE_CONFIG || {};
const $ = (id) => document.getElementById(id);
const state = { drafts: [], currentId: null, saveTimers: new Map(), history: [], historyIndex: -1, restoring: false, mode: 'edit', app: null, auth: null, db: null, user: null, unsubscribe: null, editingDirty: false, remoteReady: false, firebase: null, firebaseReady: false, snapshotCount: 0, diagnostic: { remoteIds: [], localIds: [], mergedIds: [], draftIds: [] } };
const titleInput = $('titleInput'), bodyInput = $('bodyInput'), preview = $('preview'), workspace = $('workspace'), editorMirror = $('editorMirror'), editorStack = $('editorStack');

function escapeHtml(value) { return value.replace(/[&<>\"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c])); }
function markdownToHtml(markdown) { const lines = markdown.replace(/\r/g, '').split('\n'); let html = '', list = null, paragraph = []; const inline = (text) => escapeHtml(text).replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/\*([^*]+)\*/g, '<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>'); const flush = () => { if (paragraph.length) { html += `<p>${paragraph.map(inline).join('<br>')}</p>`; paragraph = []; } }; const close = () => { if (list) { html += `</${list}>`; list = null; } }; lines.forEach((line) => { const heading = line.match(/^(#{1,3})\s+(.+)/), quote = line.match(/^>\s?(.*)/), bullet = line.match(/^[-*+]\s+(.+)/), numbered = line.match(/^\d+\.\s+(.+)/); if (heading) { flush(); close(); html += `<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`; } else if (/^\s*---+\s*$/.test(line)) { flush(); close(); html += '<hr>'; } else if (quote) { flush(); close(); html += `<blockquote>${inline(quote[1])}</blockquote>`; } else if (bullet || numbered) { flush(); const kind = bullet ? 'ul' : 'ol'; if (list !== kind) { close(); html += `<${kind}>`; list = kind; } html += `<li>${inline((bullet || numbered)[1])}</li>`; } else if (!line.trim()) { flush(); close(); } else { close(); paragraph.push(line); } }); flush(); close(); return html; }
function currentDraft() { return state.drafts.find((d) => d.id === state.currentId); }
function setStatus(text, error = false) { const el = $('saveStatus'); if (!el) return; el.className = `save-status${error ? ' error' : ''}`; el.innerHTML = `<i></i>${text}`; }
function setSyncStatus(text, kind = '') { const el = $('syncStatus'); el.textContent = text; el.className = `sync-status ${kind}`; }
function updateEditorMirror() { editorMirror.innerHTML = escapeHtml(bodyInput.value).replace(/\n/g, '<span class="line-break"></span>\n'); editorStack.style.setProperty('--scrollbar-width', `${bodyInput.offsetWidth - bodyInput.clientWidth}px`); editorMirror.style.transform = `translateY(${-bodyInput.scrollTop}px)`; }
function updatePreview() { const value = bodyInput.value.trim(); preview.innerHTML = value ? markdownToHtml(value) : '<p class="placeholder">本文を入力すると、ここにプレビューが表示されます。</p>'; $('characterCount').textContent = `${bodyInput.value.length}文字`; updateEditorMirror(); }
function isConfigured() { return Boolean(config.apiKey && config.projectId && config.appId); }
function remoteDraftsRef() { return state.firebase.collection(state.db, 'users', state.user.uid, 'blogEditorDrafts'); }
function migrationRef() { return state.firebase.doc(state.db, 'users', state.user.uid, 'blogEditorMigrations', 'localStorageV1'); }
function localDrafts() { try { const data = JSON.parse(localStorage.getItem(KEY)) || []; return Array.isArray(data) ? data.map(normalizeDraft) : []; } catch { return []; } }
function pendingDeletes() { try { const data = JSON.parse(localStorage.getItem(DELETED_KEY)) || []; return new Set(Array.isArray(data) ? data : []); } catch { return new Set(); } }
function markPendingDelete(id, pending) { const ids = pendingDeletes(); pending ? ids.add(id) : ids.delete(id); localStorage.setItem(DELETED_KEY, JSON.stringify([...ids])); }
function normalizeDraft(raw) { return { id: String(raw?.id || crypto.randomUUID()), title: typeof raw?.title === 'string' ? raw.title : '無題の記事', body: typeof raw?.body === 'string' ? raw.body : '', createdAt: validDate(raw?.createdAt) || validDate(raw?.updatedAt), updatedAt: validDate(raw?.updatedAt) || validDate(raw?.createdAt), schemaVersion: Number(raw?.schemaVersion) || SCHEMA_VERSION }; }
function validDate(value) { return typeof value === 'string' && !Number.isNaN(Date.parse(value)) ? value : ''; }
function formatDateTime(value) { const date = new Date(value); if (Number.isNaN(date.getTime())) return '—'; const pad = (number) => String(number).padStart(2, '0'); return `${date.getFullYear()}/${pad(date.getMonth() + 1)}/${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`; }
function updateDraftTimestamps(draft = currentDraft()) { $('createdAtDisplay').textContent = `作成日 ${formatDateTime(draft?.createdAt)}`; $('updatedAtDisplay').textContent = `更新日 ${formatDateTime(draft?.updatedAt)}`; }
function compareDraftTime(a, b) { const at = Date.parse(a?.updatedAt || ''), bt = Date.parse(b?.updatedAt || ''); return Number.isNaN(at) || Number.isNaN(bt) ? 0 : at - bt; }
function persistLocal() { try { localStorage.setItem(KEY, JSON.stringify(state.drafts)); localStorage.setItem(CURRENT_KEY, state.currentId || ''); return true; } catch { return false; } }
async function saveRemote(draft) { await state.firebase.setDoc(state.firebase.doc(remoteDraftsRef(), draft.id), { ...draft, schemaVersion: SCHEMA_VERSION }, { merge: true }); }
async function saveDraftById(draftId) { state.saveTimers.delete(draftId); const draft = state.drafts.find((item) => item.id === draftId); if (!draft) return; if (!persistLocal()) { setSyncStatus('同期エラー', 'error'); setStatus('保存できませんでした', true); return; } setStatus('保存しました'); if (!navigator.onLine) { setSyncStatus('オフライン'); return; } if (!state.user || !state.firebaseReady) { setSyncStatus('ローカル保存済み'); return; } setSyncStatus('同期中'); try { await saveRemote(draft); if (state.currentId === draftId) state.editingDirty = false; setSyncStatus('同期済み', 'synced'); } catch (error) { setSyncStatus('同期エラー', 'error'); console.error(error); } }
function scheduleSave() { const draftId = state.currentId, draft = state.drafts.find((item) => item.id === draftId); if (!draft) return; draft.title = titleInput.value.trim() || '無題の記事'; draft.body = bodyInput.value; draft.updatedAt = new Date().toISOString(); draft.schemaVersion = SCHEMA_VERSION; updateDraftTimestamps(draft); if (!persistLocal()) { setSyncStatus('同期エラー', 'error'); setStatus('保存できませんでした', true); return; } state.editingDirty = true; setSyncStatus(navigator.onLine ? 'ローカル保存済み' : 'オフライン'); clearTimeout(state.saveTimers.get(draftId)); state.saveTimers.set(draftId, setTimeout(() => saveDraftById(draftId), 400)); }
async function flushPendingSaves() { const pendingIds = [...state.saveTimers.keys()]; const writes = pendingIds.map((draftId) => { clearTimeout(state.saveTimers.get(draftId)); state.saveTimers.delete(draftId); return saveDraftById(draftId); }); await Promise.allSettled(writes); }
function snapshot() { return { value: bodyInput.value, start: bodyInput.selectionStart, end: bodyInput.selectionEnd, scrollTop: bodyInput.scrollTop }; }
function updateHistoryButtons() { $('undoButton').disabled = state.historyIndex <= 0; $('redoButton').disabled = state.historyIndex >= state.history.length - 1; }
function resetHistory() { state.history = [snapshot()]; state.historyIndex = 0; updateHistoryButtons(); }
function recordHistory() { if (state.restoring) return; const next = snapshot(), current = state.history[state.historyIndex]; if (current && current.value === next.value && current.start === next.start && current.end === next.end) return; state.history.splice(state.historyIndex + 1); state.history.push(next); if (state.history.length > 100) state.history.shift(); state.historyIndex = state.history.length - 1; updateHistoryButtons(); }
function restoreHistory(index) { const item = state.history[index]; if (!item) return; state.restoring = true; bodyInput.value = item.value; bodyInput.setSelectionRange(item.start, item.end); bodyInput.scrollTop = item.scrollTop; state.historyIndex = index; state.restoring = false; updatePreview(); scheduleSave(); updateHistoryButtons(); bodyInput.focus(); }
function undo() { if (state.historyIndex > 0) restoreHistory(state.historyIndex - 1); } function redo() { if (state.historyIndex < state.history.length - 1) restoreHistory(state.historyIndex + 1); }
function applyEdit(replacement, start = bodyInput.selectionStart, end = bodyInput.selectionEnd) { bodyInput.setRangeText(replacement, start, end, 'end'); bodyInput.focus(); updatePreview(); recordHistory(); scheduleSave(); }
function insertText(before, after = '', fallback = '') { const start = bodyInput.selectionStart, end = bodyInput.selectionEnd, selected = bodyInput.value.slice(start, end) || fallback; applyEdit(before + selected + after, start, end); }
function toolbar(action) { if (action === 'undo') return undo(); if (action === 'redo') return redo(); if (action === 'linebreak') return applyEdit('  \n'); if (action === 'paragraph') return applyEdit('\n\n'); if (action === 'heading' || action === 'subheading') { const start = bodyInput.selectionStart, lineStart = bodyInput.value.lastIndexOf('\n', start - 1) + 1, endAt = bodyInput.value.indexOf('\n', start), lineEnd = endAt === -1 ? bodyInput.value.length : endAt, content = bodyInput.value.slice(lineStart, lineEnd).replace(/^\s*#{1,}\s*/, '').trimStart(); return applyEdit(`${'#'.repeat(action === 'heading' ? 2 : 3)} ${content}`, lineStart, lineEnd); } const map = { bold: ['**','**','太字'], bullet: ['- ','','項目'], number: ['1. ','','項目'], quote: ['> ','','引用文'], link: ['[','](https://example.com)','リンク文字'], rule: ['\n---\n',''] }; if (map[action]) insertText(...map[action]); }
function setEditorMode(mode, persist = true) { if (window.matchMedia('(max-width: 700px)').matches && mode === 'split') mode = 'edit'; state.mode = mode; workspace.className = `workspace mode-${mode}`; $('editorView').classList.toggle('single-mode', mode !== 'split'); [['editTab','edit'], ['previewTab','preview'], ['splitTab','split']].forEach(([id, value]) => { $(id).classList.toggle('active', value === mode); $(id).setAttribute('aria-selected', String(value === mode)); }); if (persist) localStorage.setItem(VIEW_KEY, mode); }
function loadDraft(id, { remote = false } = {}) { const draft = state.drafts.find((d) => d.id === id); if (!draft) return; if (state.editingDirty && id === state.currentId && remote) { setSyncStatus('ローカル保存済み'); return; } state.currentId = id; persistLocal(); titleInput.value = draft.title === '無題の記事' ? '' : draft.title; bodyInput.value = draft.body; state.editingDirty = false; updatePreview(); updateDraftTimestamps(draft); resetHistory(); showView('editor'); bodyInput.focus(); }
function newDraft() { const now = new Date().toISOString(), draft = { id: crypto.randomUUID(), title: '無題の記事', body: '', createdAt: now, updatedAt: now, schemaVersion: SCHEMA_VERSION }; state.drafts.unshift(draft); state.currentId = draft.id; titleInput.value = ''; bodyInput.value = ''; updatePreview(); updateDraftTimestamps(draft); resetHistory(); void saveDraftById(draft.id); showView('editor'); titleInput.focus(); }
function renderList() { const list = $('draftList'), drafts = [...state.drafts].sort((a,b) => compareDraftTime(b, a)); state.diagnostic.draftIds = drafts.map((draft) => draft.id); if (!drafts.length) { list.innerHTML = '<div class="empty">下書きはまだありません。</div>'; return; } list.innerHTML = drafts.map((d) => `<article class="draft-row ${d.id === state.currentId ? 'active':''}"><div><div class="draft-title">${escapeHtml(d.title)}</div><div class="draft-excerpt">${escapeHtml(d.body.replace(/\n/g,' ').trim().slice(0,90) || '本文はまだありません。')}</div><div class="draft-dates"><span>作成 ${formatDateTime(d.createdAt)}</span><span>更新 ${formatDateTime(d.updatedAt)}</span></div></div><div class="draft-actions"><button class="small-button" data-edit="${d.id}" type="button">編集</button><button class="small-button delete" data-delete="${d.id}" type="button">削除</button></div></article>`).join(''); }
function showView(name) { ['editor','list','settings'].forEach((v) => $(`${v}View`).classList.toggle('hidden', v !== name)); document.querySelectorAll('.text-button').forEach((b) => b.classList.remove('active')); if (name === 'list') { $('draftsButton').classList.add('active'); renderList(); } if (name === 'settings') $('settingsButton').classList.add('active'); }
async function copyMarkdown() { const title = titleInput.value.trim(), markdown = title ? `# ${title}\n\n${bodyInput.value}` : bodyInput.value; await navigator.clipboard.writeText(markdown); toast('Markdownをコピーしました'); }
function noteCopyContent(title, markdown) { const noteTitle = title.trim(), titleHtml = noteTitle ? `<h1>${escapeHtml(noteTitle)}</h1>` : '', bodyHtml = markdownToHtml(markdown), html = `<article>${titleHtml}${titleHtml && bodyHtml ? '<p><br></p>' : ''}${bodyHtml}</article>`, plain = noteTitle ? `${noteTitle}\n\n${markdown}` : markdown; return { html, plain }; }
function copyRichTextFallback(html, plain) { const selection = window.getSelection(), source = document.createElement('div'), onCopy = (event) => { if (!event.clipboardData) return; event.preventDefault(); event.clipboardData.setData('text/html', html); event.clipboardData.setData('text/plain', plain); }; source.contentEditable = 'true'; source.style.cssText = 'position:fixed;left:-9999px;top:0;opacity:0;'; source.innerHTML = html; document.body.append(source); document.addEventListener('copy', onCopy); try { const range = document.createRange(); range.selectNodeContents(source); selection?.removeAllRanges(); selection?.addRange(range); return document.execCommand('copy'); } finally { document.removeEventListener('copy', onCopy); source.remove(); } }
async function copyForNote() { const { html, plain } = noteCopyContent(titleInput.value, bodyInput.value); let copied = false; if (window.ClipboardItem && navigator.clipboard?.write) try { await navigator.clipboard.write([new ClipboardItem({ 'text/html': new Blob([html], {type:'text/html'}), 'text/plain': new Blob([plain], {type:'text/plain'}) })]); copied = true; } catch {} if (!copied) copied = copyRichTextFallback(html, plain); if (!copied) await navigator.clipboard.writeText(plain); toast('note用の書式でコピーしました'); }
function download() { const blob = new Blob([bodyInput.value],{type:'text/markdown;charset=utf-8'}), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = `${(titleInput.value || 'untitled').replace(/[\\/:*?"<>|]/g,'_')}.md`; a.click(); URL.revokeObjectURL(url); }
let toastTimer; function toast(message) { const el = $('toast'); el.textContent = message; el.classList.add('visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('visible'), 2200); }

// 一時的な同期診断: IDと状態だけをコピーし、本文・タイトル・メールアドレスは扱わない。
function diagnosticBrowserName() { const ua = navigator.userAgent; if (ua.includes('Firefox/')) return 'Firefox'; if (ua.includes('Edg/')) return 'Microsoft Edge'; if (ua.includes('Chrome/')) return 'Chrome'; if (ua.includes('Safari/')) return 'Safari'; return '不明'; }
function diagnosticList(ids) { return ids.length ? ids.map((id) => `- ${id}`).join('\n') : '- （なし）'; }
function diagnosticText() { const data = state.diagnostic, deleted = [...pendingDeletes()]; return `【Blog Editor 同期診断】\n\nブラウザ: ${diagnosticBrowserName()}\nprojectId: ${config.projectId || '未設定'}\nuid: ${state.user?.uid || '未ログイン'}\n同期状態: ${$('syncStatus').textContent}\ncurrentId: ${state.currentId || '（なし）'}\n\nremoteIds:\n${diagnosticList(data.remoteIds)}\n\nlocalIds:\n${diagnosticList(data.localIds)}\n\nmergedIds:\n${diagnosticList(data.mergedIds)}\n\ndraftIds:\n${diagnosticList(data.draftIds)}\n\ndeletedIds:\n${diagnosticList(deleted)}\n\nsnapshotCount: ${state.snapshotCount}`; }
async function copyDiagnostic() { const text = diagnosticText(); try { if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(text); else if (!copyRichTextFallback('', text)) throw new Error('Clipboard API is unavailable'); toast('診断情報をコピーしました'); } catch (error) { toast('診断情報をコピーできませんでした'); console.error('診断情報のコピーに失敗しました', error); } }

function updateStorageUi() { const loggedIn = Boolean(state.user); $('storageDescription').textContent = loggedIn ? 'この端末へ保存後、Firestoreにも同期します。' : 'この端末のブラウザ（localStorage）に保存されます。'; $('storageLocation').value = loggedIn ? 'localStorage + Firestore' : 'localStorage'; }
async function updateMigrationPanel() { const panel = $('migrationPanel'); if (!state.user) return panel.classList.add('hidden'); const local = localDrafts(); const marker = await state.firebase.getDoc(migrationRef()); if (!local.length || marker.exists()) return panel.classList.add('hidden'); $('migrationMessage').textContent = `この端末のlocalStorageに${local.length}件の下書きがあります。確認後にFirestoreへコピーできます。ローカルデータは削除しません。`; panel.classList.remove('hidden'); }
async function migrateLocal() { if (!state.user) return; const local = localDrafts(); if (!local.length) return; $('migrateLocalButton').disabled = true; setSyncStatus('同期中'); try { for (const draft of local) { const target = state.firebase.doc(remoteDraftsRef(), draft.id), remote = await state.firebase.getDoc(target); if (!remote.exists() || compareDraftTime(draft, normalizeDraft(remote.data())) > 0) await state.firebase.setDoc(target, draft, { merge: true }); } await state.firebase.setDoc(migrationRef(), { completedAt: new Date().toISOString(), source: KEY, count: local.length, schemaVersion: SCHEMA_VERSION }); $('migrationPanel').classList.add('hidden'); setSyncStatus('同期済み', 'synced'); toast(`${local.length}件をFirestoreへコピーしました`); } catch (error) { setSyncStatus('同期エラー', 'error'); toast('移行できませんでした（ローカル下書きは保持されています）'); console.error(error); } finally { $('migrateLocalButton').disabled = false; } }
function mergeDrafts(remoteDrafts) { const deleted = pendingDeletes(), local = localDrafts(), merged = new Map(local.map((draft) => [draft.id, draft])); remoteDrafts.forEach((remote) => { if (deleted.has(remote.id)) return; const current = merged.get(remote.id); if (!current || compareDraftTime(remote, current) >= 0) merged.set(remote.id, remote); }); const next = [...merged.values()]; state.diagnostic.localIds = local.map((draft) => draft.id); state.diagnostic.remoteIds = remoteDrafts.map((draft) => draft.id); state.diagnostic.mergedIds = next.map((draft) => draft.id); return next; }
function startRemoteSync() { state.unsubscribe?.(); const activeUid = state.user.uid; state.remoteReady = false; state.unsubscribe = state.firebase.onSnapshot(state.firebase.query(remoteDraftsRef(), state.firebase.orderBy('updatedAt', 'desc')), (snapshot) => { if (state.user?.uid !== activeUid) return; state.snapshotCount += 1; const remote = snapshot.docs.map((item) => normalizeDraft(item.data())); state.diagnostic.remoteIds = remote.map((draft) => draft.id); const next = mergeDrafts(remote); const currentRemote = next.find((draft) => draft.id === state.currentId); state.drafts = next; state.remoteReady = true; persistLocal(); if (currentRemote && !state.editingDirty) loadDraft(currentRemote.id, { remote: true }); else if (!state.currentId && next.length) loadDraft(next[0].id, { remote: true }); renderList(); setSyncStatus('同期済み', 'synced'); }, (error) => { setSyncStatus(navigator.onLine ? '同期エラー' : 'オフライン', 'error'); console.error(error); }); }
async function handleAuth(user) { await flushPendingSaves(); state.unsubscribe?.(); state.unsubscribe = null; state.user = user; state.editingDirty = false; $('loginButton').hidden = Boolean(user); $('logoutButton').hidden = !user; updateStorageUi(); if (!user) { state.drafts = localDrafts(); state.currentId = localStorage.getItem(CURRENT_KEY) || null; setSyncStatus(navigator.onLine ? 'ローカル保存済み' : 'オフライン'); if (state.currentId && state.drafts.some((draft) => draft.id === state.currentId)) loadDraft(state.currentId); else if (state.drafts.length) loadDraft(state.drafts[0].id); else newDraft(); $('migrationPanel').classList.add('hidden'); return; } setSyncStatus('同期中'); startRemoteSync(); try { await updateMigrationPanel(); } catch (error) { setSyncStatus('同期エラー', 'error'); console.error(error); } }
async function logout() { await flushPendingSaves(); try { await state.firebase.signOut(state.auth); } catch (error) { setSyncStatus('同期エラー', 'error'); console.error(error); } }
async function setupFirebase() { $('loginButton').disabled = true; if (!isConfigured()) { setSyncStatus(navigator.onLine ? 'ローカル保存済み' : 'オフライン'); return; } try { const [app, auth, firestore] = await Promise.all([import('https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js'), import('https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js'), import('https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js')]); state.firebase = { ...app, ...auth, ...firestore }; state.app = state.firebase.initializeApp(config); state.auth = state.firebase.getAuth(state.app); state.db = state.firebase.getFirestore(state.app); state.firebaseReady = true; $('loginButton').disabled = false; state.firebase.onAuthStateChanged(state.auth, handleAuth); } catch (error) { setSyncStatus(navigator.onLine ? 'ローカル保存済み' : 'オフライン'); console.error('Firebaseを利用できません。ローカル保存を継続します。', error); } }
function signInWithGoogle() { if (!state.firebaseReady || !state.auth) { setSyncStatus('同期エラー', 'error'); console.error('Firebase Authの初期化前にログインが要求されました'); return; } const provider = new state.firebase.GoogleAuthProvider(); state.firebase.signInWithPopup(state.auth, provider).catch((error) => { setSyncStatus('同期エラー', 'error'); console.error('Googleログインに失敗しました', error); }); }
function init() { document.body.dataset.appVersion = VERSION; $('appVersion').textContent = `v${VERSION}`; state.drafts = localDrafts(); try { state.mode = localStorage.getItem(VIEW_KEY) || 'edit'; state.currentId = localStorage.getItem(CURRENT_KEY) || null; } catch {} if (state.currentId && state.drafts.some((draft) => draft.id === state.currentId)) loadDraft(state.currentId); else if (state.drafts.length) loadDraft(state.drafts[0].id); else newDraft(); setEditorMode(state.mode, false); setupFirebase(); }

titleInput.addEventListener('input', scheduleSave); bodyInput.addEventListener('input', () => { updatePreview(); recordHistory(); scheduleSave(); }); bodyInput.addEventListener('scroll', updateEditorMirror); bodyInput.addEventListener('keydown', (event) => { const modifier = event.ctrlKey || event.metaKey; if (modifier && event.key.toLowerCase() === 'z') { event.preventDefault(); event.shiftKey ? redo() : undo(); return; } if (event.ctrlKey && event.key.toLowerCase() === 'y') { event.preventDefault(); redo(); return; } if (event.key === 'Enter') { event.preventDefault(); event.shiftKey ? applyEdit('  \n') : applyEdit('\n\n'); } });
document.querySelector('.toolbar').addEventListener('click',(e) => { if (e.target.dataset.action) toolbar(e.target.dataset.action); }); $('markdownCopyButton').addEventListener('click',() => copyMarkdown().catch(() => toast('コピーできませんでした'))); $('noteCopyButton').addEventListener('click',() => copyForNote().catch(() => toast('コピーできませんでした'))); $('downloadButton').addEventListener('click',download); $('newButton').addEventListener('click',newDraft); $('listNewButton').addEventListener('click',newDraft); $('homeButton').addEventListener('click',() => showView('editor')); $('draftsButton').addEventListener('click',() => showView('list')); $('settingsButton').addEventListener('click',() => showView('settings')); $('loginButton').addEventListener('click',signInWithGoogle); $('logoutButton').addEventListener('click',logout); $('migrateLocalButton').addEventListener('click',migrateLocal); $('copyDiagnosticButton').addEventListener('click',copyDiagnostic); $('draftList').addEventListener('click',async (e) => { const {edit,delete:del} = e.target.dataset; if (edit) loadDraft(edit); if (del && confirm('この下書きを削除しますか？')) { const wasCurrent = state.currentId === del; state.drafts = state.drafts.filter((draft) => draft.id !== del); persistLocal(); if (wasCurrent) state.drafts[0] ? loadDraft(state.drafts[0].id) : newDraft(); renderList(); if (!state.user || !state.firebaseReady) { setSyncStatus(navigator.onLine ? 'ローカル保存済み' : 'オフライン'); return; } markPendingDelete(del, true); setSyncStatus('同期中'); try { await state.firebase.deleteDoc(state.firebase.doc(remoteDraftsRef(), del)); markPendingDelete(del, false); setSyncStatus('同期済み', 'synced'); } catch (error) { setSyncStatus('同期エラー', 'error'); toast('Firestoreから削除できませんでした（この端末では削除済みです）'); console.error(error); } } }); [['editTab','edit'], ['previewTab','preview'], ['splitTab','split']].forEach(([id, mode]) => $(id).addEventListener('click', () => setEditorMode(mode))); window.addEventListener('online', () => { if (!state.user) setSyncStatus('ローカル保存済み'); }); window.addEventListener('offline', () => setSyncStatus('オフライン')); window.addEventListener('pagehide', () => { void flushPendingSaves(); }); window.addEventListener('resize', () => { if (window.matchMedia('(max-width: 700px)').matches && state.mode === 'split') setEditorMode('edit'); updateEditorMirror(); });
init();
