const VERSION = '2026.07.23-01';
const KEY = 'orangemania-blog-editor-v1';
const VIEW_KEY = 'orangemania-blog-editor-view-v1';
const $ = (id) => document.getElementById(id);
const state = { drafts: [], currentId: null, timer: null, history: [], historyIndex: -1, restoring: false, mode: 'edit' };
const titleInput = $('titleInput'), bodyInput = $('bodyInput'), preview = $('preview'), workspace = $('workspace'), editorMirror = $('editorMirror'), editorStack = $('editorStack');
function escapeHtml(value) { return value.replace(/[&<>\"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[c])); }
function inlineMarkdown(text) { return escapeHtml(text).replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/\*([^*]+)\*/g, '<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>'); }
function markdownToHtml(markdown) { const lines = markdown.replace(/\r/g, '').split('\n'); let html = '', list = null, paragraph = []; const flush = () => { if (paragraph.length) { html += `<p>${paragraph.map(inlineMarkdown).join('<br>')}</p>`; paragraph = []; } }; const close = () => { if (list) { html += `</${list}>`; list = null; } }; lines.forEach((line) => { const heading = line.match(/^(#{1,3})\s+(.+)/), quote = line.match(/^>\s?(.*)/), bullet = line.match(/^[-*+]\s+(.+)/), numbered = line.match(/^\d+\.\s+(.+)/); if (heading) { flush(); close(); html += `<h${heading[1].length}>${inlineMarkdown(heading[2])}</h${heading[1].length}>`; } else if (/^\s*---+\s*$/.test(line)) { flush(); close(); html += '<hr>'; } else if (quote) { flush(); close(); html += `<blockquote>${inlineMarkdown(quote[1])}</blockquote>`; } else if (bullet || numbered) { flush(); const kind = bullet ? 'ul' : 'ol'; if (list !== kind) { close(); html += `<${kind}>`; list = kind; } html += `<li>${inlineMarkdown((bullet || numbered)[1])}</li>`; } else if (!line.trim()) { flush(); close(); } else { close(); paragraph.push(line); } }); flush(); close(); return html; }
function currentDraft() { return state.drafts.find((d) => d.id === state.currentId); }
function setStatus(text, error = false) { const el = $('saveStatus'); if (!el) return; el.className = `save-status${error ? ' error' : ''}`; el.innerHTML = `<i></i>${text}`; }
function updateEditorMirror() { editorMirror.innerHTML = escapeHtml(bodyInput.value).replace(/\n/g, '<span class="line-break"></span>\n'); const scrollbarWidth = bodyInput.offsetWidth - bodyInput.clientWidth; editorStack.style.setProperty('--scrollbar-width', `${scrollbarWidth}px`); editorMirror.style.transform = `translateY(${-bodyInput.scrollTop}px)`; }
function updatePreview() { const value = bodyInput.value.trim(); preview.innerHTML = value ? markdownToHtml(value) : '<p class="placeholder">本文を入力すると、ここにプレビューが表示されます。</p>'; $('characterCount').textContent = `${bodyInput.value.length}文字`; updateEditorMirror(); }
function save() { const draft = currentDraft(); if (!draft) return; draft.title = titleInput.value.trim() || '無題の記事'; draft.body = bodyInput.value; draft.updatedAt = new Date().toISOString(); try { localStorage.setItem(KEY, JSON.stringify(state.drafts)); setStatus('保存しました'); } catch { setStatus('保存できませんでした', true); } }
function scheduleSave() { setStatus('保存中…'); clearTimeout(state.timer); state.timer = setTimeout(save, 400); }
function snapshot() { return { value: bodyInput.value, start: bodyInput.selectionStart, end: bodyInput.selectionEnd, scrollTop: bodyInput.scrollTop }; }
function updateHistoryButtons() { $('undoButton').disabled = state.historyIndex <= 0; $('redoButton').disabled = state.historyIndex >= state.history.length - 1; }
function resetHistory() { state.history = [snapshot()]; state.historyIndex = 0; updateHistoryButtons(); }
function recordHistory() { if (state.restoring) return; const next = snapshot(), current = state.history[state.historyIndex]; if (current && current.value === next.value && current.start === next.start && current.end === next.end) return; state.history.splice(state.historyIndex + 1); state.history.push(next); if (state.history.length > 100) state.history.shift(); state.historyIndex = state.history.length - 1; updateHistoryButtons(); }
function restoreHistory(index) { const item = state.history[index]; if (!item) return; state.restoring = true; bodyInput.value = item.value; bodyInput.setSelectionRange(item.start, item.end); bodyInput.scrollTop = item.scrollTop; state.historyIndex = index; state.restoring = false; updatePreview(); scheduleSave(); updateHistoryButtons(); bodyInput.focus(); }
function undo() { if (state.historyIndex > 0) restoreHistory(state.historyIndex - 1); } function redo() { if (state.historyIndex < state.history.length - 1) restoreHistory(state.historyIndex + 1); }
function applyEdit(replacement, start = bodyInput.selectionStart, end = bodyInput.selectionEnd) { bodyInput.setRangeText(replacement, start, end, 'end'); bodyInput.focus(); updatePreview(); recordHistory(); scheduleSave(); }
function insertText(before, after = '', fallback = '') { const start = bodyInput.selectionStart, end = bodyInput.selectionEnd, selected = bodyInput.value.slice(start, end) || fallback; applyEdit(before + selected + after, start, end); }
function insertParagraph() { applyEdit('\n\n'); } function insertLinebreak() { applyEdit('  \n'); }
function replaceHeading(level) { const start = bodyInput.selectionStart, lineStart = bodyInput.value.lastIndexOf('\n', start - 1) + 1, endAt = bodyInput.value.indexOf('\n', start), lineEnd = endAt === -1 ? bodyInput.value.length : endAt, content = bodyInput.value.slice(lineStart, lineEnd).replace(/^\s*#{1,}\s*/, '').trimStart(), replacement = `${'#'.repeat(level)} ${content}`; applyEdit(replacement, lineStart, lineEnd); }
function toolbar(action) { if (action === 'undo') return undo(); if (action === 'redo') return redo(); if (action === 'linebreak') return insertLinebreak(); if (action === 'paragraph') return insertParagraph(); if (action === 'heading') return replaceHeading(2); if (action === 'subheading') return replaceHeading(3); const map = { bold: ['**','**','太字'], bullet: ['- ','','項目'], number: ['1. ','','項目'], quote: ['> ','','引用文'], link: ['[','](https://example.com)','リンク文字'], rule: ['\n---\n',''] }; if (map[action]) insertText(...map[action]); }
function setEditorMode(mode, persist = true) { if (window.matchMedia('(max-width: 700px)').matches && mode === 'split') mode = 'edit'; state.mode = mode; workspace.classList.remove('mode-edit', 'mode-preview', 'mode-split'); workspace.classList.add(`mode-${mode}`); $('editorView').classList.toggle('single-mode', mode !== 'split'); [['editTab','edit'], ['previewTab','preview'], ['splitTab','split']].forEach(([id, value]) => { const tab = $(id); tab.classList.toggle('active', value === mode); tab.setAttribute('aria-selected', String(value === mode)); }); if (persist) localStorage.setItem(VIEW_KEY, mode); }
function loadDraft(id) { const draft = state.drafts.find((d) => d.id === id); if (!draft) return; state.currentId = id; titleInput.value = draft.title === '無題の記事' ? '' : draft.title; bodyInput.value = draft.body; updatePreview(); resetHistory(); showView('editor'); setStatus('保存しました'); bodyInput.focus(); }
function newDraft() { const draft = { id: crypto.randomUUID(), title: '無題の記事', body: '', updatedAt: new Date().toISOString() }; state.drafts.unshift(draft); state.currentId = draft.id; titleInput.value = ''; bodyInput.value = ''; updatePreview(); resetHistory(); save(); showView('editor'); titleInput.focus(); }
function renderList() { const list = $('draftList'), drafts = [...state.drafts].sort((a,b) => new Date(b.updatedAt)-new Date(a.updatedAt)); if (!drafts.length) { list.innerHTML = '<div class="empty">下書きはまだありません。</div>'; return; } list.innerHTML = drafts.map((d) => `<article class="draft-row ${d.id === state.currentId ? 'active':''}"><div><div class="draft-title">${escapeHtml(d.title)}</div><div class="draft-excerpt">${escapeHtml(d.body.replace(/\n/g,' ').trim().slice(0,90) || '本文はまだありません。')}</div><div class="draft-date">更新 ${new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d.updatedAt))}</div></div><div class="draft-actions"><button class="small-button" data-edit="${d.id}" type="button">編集</button><button class="small-button delete" data-delete="${d.id}" type="button">削除</button></div></article>`).join(''); }
function showView(name) { ['editor','list','settings'].forEach((v) => $(`${v}View`).classList.toggle('hidden', v !== name)); document.querySelectorAll('.text-button').forEach((b) => b.classList.remove('active')); if (name === 'list') { $('draftsButton').classList.add('active'); renderList(); } if (name === 'settings') $('settingsButton').classList.add('active'); }
async function copyMarkdown() { await navigator.clipboard.writeText(bodyInput.value); toast('Markdownをコピーしました'); } function noteCopyContent(title, markdown) { const noteTitle = title.trim(), titleHtml = noteTitle ? `<h1>${escapeHtml(noteTitle)}</h1>` : '', bodyHtml = markdownToHtml(markdown), html = `<article>${titleHtml}${titleHtml && bodyHtml ? '<p><br></p>' : ''}${bodyHtml}</article>`, plain = noteTitle ? `${noteTitle}\n\n${markdown}` : markdown; return { html, plain }; } function copyRichTextFallback(html, plain) { const selection = window.getSelection(), savedRanges = selection ? Array.from({ length: selection.rangeCount }, (_, index) => selection.getRangeAt(index).cloneRange()) : [], activeElement = document.activeElement, source = document.createElement('div'), onCopy = (event) => { if (!event.clipboardData) return; event.preventDefault(); event.clipboardData.setData('text/html', html); event.clipboardData.setData('text/plain', plain); }; source.contentEditable = 'true'; source.setAttribute('aria-hidden', 'true'); source.style.cssText = 'position:fixed;left:-9999px;top:0;opacity:0;pointer-events:none;'; source.innerHTML = html; document.body.append(source); document.addEventListener('copy', onCopy); try { const range = document.createRange(); range.selectNodeContents(source); selection?.removeAllRanges(); selection?.addRange(range); return document.execCommand('copy'); } finally { document.removeEventListener('copy', onCopy); source.remove(); if (selection) { selection.removeAllRanges(); savedRanges.forEach((range) => selection.addRange(range)); } try { activeElement?.focus({ preventScroll: true }); } catch { activeElement?.focus(); } } } async function copyForNote() { const { html, plain } = noteCopyContent(titleInput.value, bodyInput.value); let copied = false; if (window.ClipboardItem && navigator.clipboard?.write) { try { await navigator.clipboard.write([new ClipboardItem({ 'text/html': new Blob([html], {type:'text/html'}), 'text/plain': new Blob([plain], {type:'text/plain'}) })]); copied = true; } catch {} } if (!copied) copied = copyRichTextFallback(html, plain); if (!copied) { if (!navigator.clipboard?.writeText) throw new Error('Clipboard API is unavailable'); await navigator.clipboard.writeText(plain); } toast('note用の書式でコピーしました'); }
function download() { const blob = new Blob([bodyInput.value],{type:'text/markdown;charset=utf-8'}), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = `${(titleInput.value || 'untitled').replace(/[\\/:*?"<>|]/g,'_')}.md`; a.click(); URL.revokeObjectURL(url); } let toastTimer; function toast(message) { const el = $('toast'); el.textContent = message; el.classList.add('visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('visible'), 2200); }
function init() { document.body.dataset.appVersion = VERSION; $('appVersion').textContent = `v${VERSION}`; try { state.drafts = JSON.parse(localStorage.getItem(KEY)) || []; } catch { state.drafts=[]; } try { state.mode = localStorage.getItem(VIEW_KEY) || 'edit'; } catch { state.mode = 'edit'; } if (state.drafts.length) loadDraft(state.drafts[0].id); else newDraft(); setEditorMode(state.mode, false); }
titleInput.addEventListener('input', scheduleSave); bodyInput.addEventListener('input', () => { updatePreview(); recordHistory(); scheduleSave(); }); bodyInput.addEventListener('scroll', updateEditorMirror); bodyInput.addEventListener('keydown', (event) => { const modifier = event.ctrlKey || event.metaKey; if (modifier && event.key.toLowerCase() === 'z') { event.preventDefault(); event.shiftKey ? redo() : undo(); return; } if (event.ctrlKey && event.key.toLowerCase() === 'y') { event.preventDefault(); redo(); return; } if (event.key === 'Enter') { event.preventDefault(); event.shiftKey ? insertLinebreak() : insertParagraph(); } });
document.querySelector('.toolbar').addEventListener('click',(e) => { if (e.target.dataset.action) toolbar(e.target.dataset.action); }); $('markdownCopyButton').addEventListener('click',() => copyMarkdown().catch(() => toast('コピーできませんでした'))); $('noteCopyButton').addEventListener('click',() => copyForNote().catch(() => toast('コピーできませんでした'))); $('downloadButton').addEventListener('click',download); $('newButton').addEventListener('click',newDraft); $('listNewButton').addEventListener('click',newDraft); $('homeButton').addEventListener('click',() => showView('editor')); $('draftsButton').addEventListener('click',() => showView('list')); $('settingsButton').addEventListener('click',() => showView('settings')); $('draftList').addEventListener('click',(e) => { const {edit,delete:del} = e.target.dataset; if(edit) loadDraft(edit); if(del && confirm('この下書きを削除しますか？')) { state.drafts = state.drafts.filter((d) => d.id !== del); if(state.currentId === del) state.drafts[0] ? loadDraft(state.drafts[0].id) : newDraft(); save(); renderList(); } }); [['editTab','edit'], ['previewTab','preview'], ['splitTab','split']].forEach(([id, mode]) => $(id).addEventListener('click', () => setEditorMode(mode))); window.addEventListener('resize', () => { if (window.matchMedia('(max-width: 700px)').matches && state.mode === 'split') setEditorMode('edit'); updateEditorMirror(); }); init();