/* イロイロキロク: Firestoreを正式保存先にする画面ロジック。 */
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { GoogleAuthProvider, getAuth, onAuthStateChanged, signInWithPopup, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getFirestore, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, writeBatch } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const VERSION='2026.07.13-15'; const LEGACY_KEY='orangememo-notes-v1';
const CATEGORY_COLOR_PALETTE=['#FF7F00','#3A86D4','#D94F8A','#38A169','#7E5FC4','#E25555','#1E9A8A','#FFD400'];
const LEGACY_DEFAULT_CATEGORY_COLORS={app:['#fff0e8','#FF7F00'],manga:['#fff8d8','#FFD400'],blog:['#eaf5ff','#3A86D4'],cooking:['#ecf8ed','#38A169'],shopping:['#f5edff','#7E5FC4'],research:['#e9f7f5','#1E9A8A']};
const STANDARD_CATEGORY_COLOR_MIGRATIONS={manga:['#e0aa16','#FFD400']};
const DEFAULT_CATEGORIES=[['app','アプリ','#FF7F00'],['manga','漫画','#FFD400'],['blog','ブログ','#3A86D4'],['cooking','料理','#38A169'],['shopping','買い物','#7E5FC4'],['research','あとで調べる','#1E9A8A']].map(([id,name,color],order)=>({id,name,color,order}));
const $=id=>document.getElementById(id); const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`; const config=window.IROIRO_FIREBASE_CONFIG||{};
let app,auth,db,currentUser=null,notes=[],categories=[],selectedCategory='all',editingNote=null,saveTimer=null,unsubscribeNotes=null,unsubscribeSettings=null,settingsCreatingForUid='',closingEditor=false,deletingNote=false,pendingCategoryId='',pendingType='',categoryDragState=null,itemDragState=null,editRevision=0,savedRevision=0,requestedRevision=0,saveInProgress=false,savePromise=Promise.resolve(true),editorSession='';
function configured(){return Boolean(config.apiKey&&config.projectId&&config.appId)}
function refs(){return{notes:collection(db,'users',currentUser.uid,'iroiroNotes'),settings:doc(db,'users',currentUser.uid,'iroiroSettings','main'),migration:doc(db,'users',currentUser.uid,'iroiroMigrations','localStorageV1')}}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function categoryColor(value,fallback='#6b7280'){return/^#[0-9a-f]{6}$/i.test(String(value||''))?String(value).toUpperCase():fallback}
function categoryTextColor(value){const hex=categoryColor(value).slice(1),red=parseInt(hex.slice(0,2),16),green=parseInt(hex.slice(2,4),16),blue=parseInt(hex.slice(4,6),16);return(red*299+green*587+blue*114)/1000>=160?'#2D2926':'#FFFFFF'}
function categoryStyle(value){const color=categoryColor(value);return`style="--category-color:${color};--category-text:${categoryTextColor(color)}"`}
function colorChoices(selected){const current=categoryColor(selected);return CATEGORY_COLOR_PALETTE.map(color=>`<button type="button" class="category-color-choice ${current===color?'selected':''}" data-color-choice="${color}" style="--choice-color:${color}" aria-label="${color}を選択" aria-pressed="${current===color}"></button>`).join('')}
/* Timestamp、Date、旧ISO文字列、serverTimestamp反映前のnullを同じ経路で扱う。 */
function toDate(value){if(!value)return null;let date=null;if(value instanceof Date)date=new Date(value);else if(typeof value.toDate==='function')date=value.toDate();else if(typeof value.toMillis==='function')date=new Date(value.toMillis());else if(typeof value==='object'&&typeof value.seconds==='number')date=new Date(value.seconds*1000+(value.nanoseconds||0)/1e6);else if(typeof value==='number'||typeof value==='string')date=new Date(value);return date&&!Number.isNaN(date.getTime())?date:null}
function dateMillis(value,fallback=0){return toDate(value)?.getTime()??fallback}
function formatDate(value){const date=toDate(value);return date?new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(date):'日時不明'}
function shortDate(value){const date=toDate(value);return date?new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric'}).format(date):'日時不明'}
function orderedCategories(list){return list.map((category,index)=>({...category,order:Number.isFinite(Number(category.order))?Number(category.order):index})).sort((a,b)=>a.order-b.order)}
function getCategory(id){return categories.find(c=>c.id===id)}
function displayTitle(n){return n.title.trim()||((n.type==='text'?n.content:n.items.map(i=>i.text).join(' ')).trim().slice(0,48)||'無題のメモ')}
function copyItems(items=[]){return(Array.isArray(items)?items:[]).map((item,index)=>({id:String(item.id||uid()),text:String(item.text||''),checked:Boolean(item.checked),order:Number.isFinite(item.order)?item.order:index}))}
function ensureFormatStores(note){if(!note)return;note.contentByType=note.contentByType&&typeof note.contentByType==='object'?note.contentByType:{};note.itemsByType=note.itemsByType&&typeof note.itemsByType==='object'?note.itemsByType:{};if(!Object.prototype.hasOwnProperty.call(note.contentByType,'text'))note.contentByType.text=note.type==='text'?String(note.content||''):'';['bullet','checklist'].forEach(type=>{if(!Array.isArray(note.itemsByType[type]))note.itemsByType[type]=note.type===type?copyItems(note.items):[]})}
function rememberCurrentFormat(note){ensureFormatStores(note);if(note.type==='text')note.contentByType.text=String(note.content||'');else note.itemsByType[note.type]=copyItems(note.items)}
function normalizeNote(id,data={}){const note={id,title:String(data.title||''),type:['text','bullet','checklist'].includes(data.type)?data.type:'text',content:String(data.content||''),items:copyItems(data.items),categoryId:String(data.categoryId||''),urls:Array.isArray(data.urls)?data.urls:[],isPinned:Boolean(data.isPinned),createdAt:data.createdAt??null,updatedAt:data.updatedAt??null,contentByType:data.contentByType,itemsByType:data.itemsByType};ensureFormatStores(note);return note}
function createNote(){const now=new Date();return{id:'',title:'',type:'text',content:'',items:[],categoryId:'',urls:[],isPinned:false,createdAt:now,updatedAt:now,contentByType:{text:''},itemsByType:{bullet:[],checklist:[]}}}
function hasMeaningfulContent(note){return Boolean(note.title.trim()||note.content.trim()||note.items.some(item=>String(item.text||'').trim())||extractUrls(note).length)}
function setStatus(message){$('syncStatus').textContent=message}
function initialize(){document.body.dataset.appVersion=VERSION;bindEvents();if(!configured()){$('syncStatus').textContent='Firebase設定が未設定です';$('loginButton').disabled=true;renderAll();return}app=initializeApp(config);auth=getAuth(app);db=getFirestore(app);onAuthStateChanged(auth,handleAuth)}
function bindEvents(){
  $('createNoteButton').onclick=()=>currentUser&&openEditor(createNote()); $('loginButton').onclick=()=>signInWithPopup(auth,new GoogleAuthProvider()).catch(e=>setStatus(`ログイン失敗: ${e.message}`)); $('logoutButton').onclick=()=>signOut(auth);
  $('searchInput').oninput=renderNotes;$('sortSelect').onchange=renderNotes;$('noteTitleInput').oninput=()=>{syncEditingNoteFromForm();scheduleSave()};$('noteContentInput').oninput=()=>{syncEditingNoteFromForm();renderLinks();scheduleSave()};$('noteCategorySelect').onchange=()=>{syncEditingNoteFromForm();scheduleSave()};
  $('closeEditorButton').onclick=e=>{e.preventDefault();closeEditor()}; $('editorDialog').addEventListener('cancel',e=>{e.preventDefault();closeEditor()});$('editorDialog').addEventListener('close',cancelItemDrag);
  $('pinButton').onclick=()=>{editingNote.isPinned=!editingNote.isPinned;updateEditor();scheduleSave()}; $('deleteNoteButton').onclick=confirmDelete;$('confirmDeleteButton').onclick=e=>{e.preventDefault();deleteCurrentNote()};
  $('addItemButton').onclick=()=>{editingNote.items.push({id:uid(),text:'',checked:false,order:editingNote.items.length});renderItems();scheduleSave()}; $('typeSwitcher').onclick=e=>{const type=e.target.dataset.type;if(type)requestTypeChange(type)};
  ['manageCategoriesButton','mobileManageCategoriesButton'].forEach(id=>$(id).onclick=openCategoryManager);$('categoryDialog').addEventListener('close',cancelCategoryDrag);$('categoryDialog').addEventListener('cancel',cancelCategoryDrag);$('addCategoryButton').onclick=addCategory;$('confirmCategoryDeleteButton').onclick=e=>{e.preventDefault();deletePendingCategory()};$('showPreviousTypeButton').onclick=e=>{e.preventDefault();applyTypeChange(pendingType,'previous');$('typeConfirmDialog').close()};$('replaceTypeContentButton').onclick=e=>{e.preventDefault();applyTypeChange(pendingType,'replace');$('typeConfirmDialog').close()};$('typeConfirmDialog').addEventListener('close',()=>{pendingType=''});
  $('migrateLocalButton').onclick=migrateLegacy;
}
function clearRealtimeListeners(){if(unsubscribeNotes){unsubscribeNotes();unsubscribeNotes=null}if(unsubscribeSettings){unsubscribeSettings();unsubscribeSettings=null}}
async function handleAuth(user){clearRealtimeListeners();settingsCreatingForUid='';currentUser=user;if(!user){notes=[];categories=[];$('loginButton').hidden=false;$('logoutButton').hidden=true;setStatus(configured()?'ログインすると同期できます':'Firebase設定が未設定です');renderAll();return}const activeUid=user.uid;$('loginButton').hidden=true;$('logoutButton').hidden=false;setStatus('同期中…');const activeSettings=doc(db,'users',activeUid,'iroiroSettings','main');const activeNotes=collection(db,'users',activeUid,'iroiroNotes');unsubscribeSettings=onSnapshot(activeSettings,snap=>{if(currentUser?.uid!==activeUid)return;if(snap.exists()&&Array.isArray(snap.data().categories)){applyRemoteCategories(snap.data().categories);return}if(settingsCreatingForUid!==activeUid){settingsCreatingForUid=activeUid;setDoc(activeSettings,{categories:structuredClone(DEFAULT_CATEGORIES),updatedAt:serverTimestamp()}).catch(e=>setStatus(`カテゴリー初期化失敗: ${e.message}`)).finally(()=>{if(settingsCreatingForUid===activeUid)settingsCreatingForUid=''})}},err=>setStatus(`カテゴリー同期失敗: ${err.message}`));unsubscribeNotes=onSnapshot(query(activeNotes,orderBy('updatedAt','desc')),snap=>{if(currentUser?.uid!==activeUid)return;notes=snap.docs.map(x=>normalizeNote(x.id,x.data()));setStatus('同期済み');renderAll()},err=>setStatus(`同期失敗: ${err.message}`));try{await checkLegacy()}catch(e){setStatus(`移行状態の確認失敗: ${e.message}`)}}
function applyRemoteCategories(nextCategories){let migrated=false;const prepared=nextCategories.map(category=>{const legacy=LEGACY_DEFAULT_CATEGORY_COLORS[category.id],standard=STANDARD_CATEGORY_COLOR_MIGRATIONS[category.id],savedColor=String(category.color||'').toLowerCase();if(legacy&&(savedColor===legacy[0]||standard&&savedColor===standard[0])){migrated=true;return{...category,color:standard?.[1]||legacy[1]}}return category});categories=orderedCategories(prepared);renderAll();refreshEditorCategoryOptions();if(migrated)saveCategories(categories)}
function refreshEditorCategoryOptions(){if(!editingNote||!$('editorDialog').open)return;const select=$('noteCategorySelect');const current=editingNote.categoryId;select.innerHTML=`<option value="">未分類</option>${categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}`;if(current===''||categories.some(c=>c.id===current)){select.value=current;return}editingNote.categoryId='';select.value='';scheduleSave()}
function openEditor(note){editingNote=structuredClone(note);ensureFormatStores(editingNote);editorSession=uid();editRevision=0;savedRevision=0;requestedRevision=0;saveInProgress=false;savePromise=Promise.resolve(true);updateEditor();$('editorDialog').showModal();setTimeout(()=>$('noteTitleInput').focus(),40)}
function syncEditingNoteFromForm(){if(!editingNote)return;editingNote.title=$('noteTitleInput').value;editingNote.content=$('noteContentInput').value;editingNote.categoryId=$('noteCategorySelect').value;rememberCurrentFormat(editingNote);editingNote.urls=extractUrls(editingNote)}
function updateEditor(){const n=editingNote;$('noteTitleInput').value=n.title;$('noteContentInput').value=n.content;$('noteCategorySelect').innerHTML=`<option value="">未分類</option>${categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}`;$('noteCategorySelect').value=n.categoryId;$('textEditor').hidden=n.type!=='text';$('itemsEditor').hidden=n.type==='text';document.querySelectorAll('#typeSwitcher button').forEach(b=>b.classList.toggle('active',b.dataset.type===n.type));$('pinButton').classList.toggle('active',n.isPinned);$('pinButton').textContent=`${n.isPinned?'★':'♧'} ピン留め`;$('createdAt').textContent=formatDate(n.createdAt);$('updatedAt').textContent=formatDate(n.updatedAt);renderItems();renderLinks();$('saveStatus').textContent='保存済み'}
function refreshRelatedLinks(){if(!editingNote)return;rememberCurrentFormat(editingNote);editingNote.urls=extractUrls(editingNote);renderLinks()}
function renderItems(){cancelItemDrag();$('itemsList').innerHTML=editingNote.items.map((item,index)=>`<div class="item-row draggable-item-row ${item.checked?'checked':''}" data-item-id="${escapeHtml(item.id)}"><input type="${editingNote.type==='checklist'?'checkbox':'button'}" ${editingNote.type==='checklist'&&item.checked?'checked':''} ${editingNote.type==='bullet'?'value="•" tabindex="-1"':''} data-check="${index}"/><input type="text" value="${escapeHtml(item.text)}" placeholder="項目を入力" data-item="${index}"/><button type="button" class="remove-item" data-remove="${index}" aria-label="項目を削除">×</button></div>`).join('');document.querySelectorAll('[data-item]').forEach(el=>{el.oninput=e=>{editingNote.items[e.target.dataset.item].text=e.target.value;refreshRelatedLinks();scheduleSave()};el.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const at=+e.target.dataset.item+1;editingNote.items.splice(at,0,{id:uid(),text:'',checked:false,order:at});editingNote.items.forEach((x,i)=>x.order=i);renderItems();refreshRelatedLinks();scheduleSave();document.querySelector(`[data-item="${at}"]`)?.focus()}}});document.querySelectorAll('[data-check]').forEach(el=>el.onchange=e=>{if(editingNote.type==='checklist'){editingNote.items[e.target.dataset.check].checked=e.target.checked;renderItems();refreshRelatedLinks();scheduleSave()}});document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=e=>{editingNote.items.splice(+e.currentTarget.dataset.remove,1);editingNote.items.forEach((x,i)=>x.order=i);renderItems();refreshRelatedLinks();scheduleSave()});document.querySelectorAll('.draggable-item-row').forEach(bindItemDrag)}
function itemDragAllowedTarget(target,touch=false){if(target.closest('input[type="checkbox"],.remove-item'))return false;return touch||!target.closest('input,button')}
function bindItemDrag(row){row.addEventListener('pointerdown',event=>{if(event.pointerType!=='mouse'||itemDragState||!itemDragAllowedTarget(event.target))return;const state={row,kind:'pointer',pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,started:false,timer:null};itemDragState=state;startItemDrag(state)});row.addEventListener('pointermove',event=>{const state=itemDragState;if(!state||state.kind!=='pointer'||state.pointerId!==event.pointerId||!state.started)return;event.preventDefault();event.stopPropagation();autoScrollItemEditor(event.clientY);updateItemDragTarget(event.clientX,event.clientY,state)});row.addEventListener('pointerup',event=>{const state=itemDragState;if(state?.kind==='pointer'&&state.pointerId===event.pointerId)finishItemDrag()});row.addEventListener('pointercancel',event=>{if(itemDragState?.kind==='pointer'&&itemDragState.pointerId===event.pointerId)cancelItemDrag()});row.addEventListener('touchstart',event=>{if(itemDragState||!itemDragAllowedTarget(event.target,true))return;const touch=event.changedTouches[0];if(!touch)return;const state={row,kind:'touch',touchId:touch.identifier,startX:touch.clientX,startY:touch.clientY,started:false,timer:null,scrollTop:document.querySelector('.editor-content')?.scrollTop||0};itemDragState=state;state.timer=setTimeout(()=>startItemDrag(state),450);document.addEventListener('touchmove',handleItemTouchMove,{passive:false});document.addEventListener('touchend',finishItemTouch,{passive:false});document.addEventListener('touchcancel',cancelItemTouch,{passive:false})},{passive:true})}
function startItemDrag(state){if(itemDragState!==state)return;state.started=true;document.activeElement?.blur();state.row.classList.add('dragging');document.body.classList.add('item-drag-active');if(state.kind==='pointer')state.row.setPointerCapture?.(state.pointerId);navigator.vibrate?.(12)}
function autoScrollItemEditor(y){const scroller=document.querySelector('.editor-content');if(!scroller)return;const rect=scroller.getBoundingClientRect(),edge=48;if(y<rect.top+edge)scroller.scrollTop-=14;else if(y>rect.bottom-edge)scroller.scrollTop+=14}
function updateItemDragTarget(x,y,state){document.querySelectorAll('.draggable-item-row').forEach(row=>row.classList.remove('drop-before','drop-after'));const target=document.elementFromPoint(x,y)?.closest('.draggable-item-row');if(!target||target===state.row)return;const before=y<target.getBoundingClientRect().top+target.getBoundingClientRect().height/2;target.classList.add(before?'drop-before':'drop-after');state.targetId=target.dataset.itemId;state.before=before}
function handleItemTouchMove(event){const state=itemDragState;if(!state||state.kind!=='touch')return;const touch=[...event.touches].find(item=>item.identifier===state.touchId);if(!touch)return;if(!state.started){if(Math.hypot(touch.clientX-state.startX,touch.clientY-state.startY)>10)cancelItemDrag();return}event.preventDefault();event.stopPropagation();autoScrollItemEditor(touch.clientY);updateItemDragTarget(touch.clientX,touch.clientY,state)}
function finishItemTouch(event){const state=itemDragState;if(!state||state.kind!=='touch'||![...event.changedTouches].some(touch=>touch.identifier===state.touchId))return;if(state.started){event.preventDefault();event.stopPropagation()}finishItemDrag()}
function cancelItemTouch(event){const state=itemDragState;if(!state||state.kind!=='touch')return;if(state.started){event.preventDefault();event.stopPropagation()}cancelItemDrag()}
function finishItemDrag(){const state=itemDragState;if(!state)return;const sourceId=state.row.dataset.itemId,targetId=state.targetId,before=state.before,started=state.started;cancelItemDrag();if(!started||!targetId||targetId===sourceId||!editingNote)return;const sourceIndex=editingNote.items.findIndex(item=>item.id===sourceId),targetIndex=editingNote.items.findIndex(item=>item.id===targetId);if(sourceIndex>=0&&targetIndex>=0)moveDraggedItem(sourceIndex,targetIndex,before)}
function cancelItemDrag(){const state=itemDragState;if(!state)return;clearTimeout(state.timer);if(state.kind==='touch'){document.removeEventListener('touchmove',handleItemTouchMove);document.removeEventListener('touchend',finishItemTouch);document.removeEventListener('touchcancel',cancelItemTouch)}state.row.classList.remove('dragging');document.querySelectorAll('.draggable-item-row').forEach(row=>row.classList.remove('drop-before','drop-after'));document.body.classList.remove('item-drag-active');itemDragState=null}
function moveDraggedItem(sourceIndex,targetIndex,before){if(!editingNote||sourceIndex===targetIndex)return;const [source]=editingNote.items.splice(sourceIndex,1);let insertAt=targetIndex;if(sourceIndex<targetIndex)insertAt--;if(!before)insertAt++;editingNote.items.splice(insertAt,0,source);editingNote.items.forEach((item,index)=>item.order=index);refreshRelatedLinks();renderItems();scheduleSave()}
function trimUrlEnding(value){return value.replace(/[。、，．！？）】」』〉》;:,.]+$/u,'')}
function extractUrls(note){const text=note.type==='text'?note.content:note.items.map(i=>i.text).join('\n');const found=text.match(/https?:\/\/[^\s<>"']+/g)||[];const links=[];for(const raw of found){const url=trimUrlEnding(raw);try{const parsed=new URL(url);if((parsed.protocol==='http:'||parsed.protocol==='https:')&&!links.some(link=>link.url===parsed.href))links.push({url:parsed.href,title:'',domain:parsed.hostname.replace(/^www\./,'')})}catch{}}return links}
function hasStoredTypeContent(note,type){ensureFormatStores(note);return type==='text'?Boolean(note.contentByType.text.trim()):note.itemsByType[type].some(item=>String(item.text||'').trim())}
function itemsFromText(content,checked=false){return String(content||'').split(/\r?\n/).map(text=>text.trim()).filter(Boolean).map((text,order)=>({id:uid(),text,checked,order}))}
function convertCurrentContent(note,targetType){if(targetType==='text'){if(note.type==='text')return String(note.content||'');return note.items.map(item=>note.type==='checklist'?`${item.checked?'☑':'☐'} ${item.text}`:item.text).filter(text=>text.trim()).join('\n')}if(note.type==='text')return itemsFromText(note.content);return note.items.filter(item=>String(item.text||'').trim()).map((item,order)=>({id:uid(),text:String(item.text||''),checked:false,order}))}
function showStoredTypeContent(note,type){ensureFormatStores(note);note.type=type;if(type==='text')note.content=note.contentByType.text||'';else note.items=copyItems(note.itemsByType[type])}
function requestTypeChange(type){if(!editingNote||deletingNote||type===editingNote.type)return;syncEditingNoteFromForm();if(hasStoredTypeContent(editingNote,type)){pendingType=type;$('typeConfirmDialog').showModal();return}applyTypeChange(type,'replace')}
function applyTypeChange(type,mode='replace'){if(!type||!editingNote)return;syncEditingNoteFromForm();if(mode==='previous')showStoredTypeContent(editingNote,type);else{const converted=convertCurrentContent(editingNote,type);editingNote.type=type;if(type==='text'){editingNote.content=converted;editingNote.contentByType.text=converted}else{editingNote.items=converted;editingNote.itemsByType[type]=copyItems(converted)}}editingNote.urls=extractUrls(editingNote);pendingType='';updateEditor();scheduleSave()}
function scheduleSave(){if(deletingNote||!editingNote)return;editRevision++;$('saveStatus').textContent='保存中…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>requestSave(),550)}
function noteData(note){rememberCurrentFormat(note);return{title:note.title, type:note.type, content:note.content, items:note.items, contentByType:note.contentByType, itemsByType:note.itemsByType, categoryId:note.categoryId, urls:note.urls, isPinned:note.isPinned}}
function captureSaveSnapshot(){syncEditingNoteFromForm();return{note:structuredClone(editingNote),session:editorSession}}
function requestSave(){requestedRevision=Math.max(requestedRevision,editRevision);if(saveInProgress)return savePromise;if(requestedRevision<=savedRevision)return Promise.resolve(true);savePromise=drainSaveQueue();return savePromise}
async function drainSaveQueue(){saveInProgress=true;try{while(savedRevision<requestedRevision){const revision=requestedRevision;const snapshot=captureSaveSnapshot();const result=await persistSnapshot(snapshot);if(!result.ok)return false;savedRevision=revision}return true}finally{saveInProgress=false}}
async function persistSnapshot(snapshot){if(!currentUser||!snapshot.note)return{ok:false};const isNew=!snapshot.note.id;if(isNew&&!hasMeaningfulContent(snapshot.note)){$('saveStatus').textContent='未保存（空のメモ）';return{ok:true,skipped:true}}$('saveStatus').textContent='保存中…';try{if(isNew){const created=await addDoc(refs().notes,{...noteData(snapshot.note),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});if(editingNote&&editorSession===snapshot.session&&!editingNote.id)editingNote.id=created.id}else await updateDoc(doc(refs().notes,snapshot.note.id),{...noteData(snapshot.note),updatedAt:serverTimestamp()});$('saveStatus').textContent='保存済み';if(editingNote&&editorSession===snapshot.session){editingNote.urls=structuredClone(snapshot.note.urls);renderLinks()}return{ok:true}}catch(e){$('saveStatus').textContent='保存できませんでした';setStatus(`保存失敗: ${e.message}`);return{ok:false,error:e}}}
async function closeEditor(){if(closingEditor||!editingNote)return;closingEditor=true;clearTimeout(saveTimer);requestedRevision=Math.max(requestedRevision,editRevision);const result=requestedRevision>savedRevision||saveInProgress?await requestSave():true;if(result){$('editorDialog').close();editingNote=null;editorSession=''}else $('saveStatus').textContent='保存できませんでした。内容を確認してもう一度お試しください。';closingEditor=false}
function renderAll(){renderCategories();renderNotes()}
function renderCategories(){const list=[{id:'all',name:'すべて',color:'#FFFFFF'},...categories,{id:'',name:'未分類',color:'#6B7280'}];const nav=c=>`<button class="category-nav-item ${selectedCategory===c.id?'active':''}" data-category="${c.id}"><span class="category-dot" style="background:${categoryColor(c.color)}"></span>${escapeHtml(c.name)}</button>`;$('sidebarCategories').innerHTML=list.map(nav).join('');$('categoryTabs').innerHTML=list.map(c=>`<button class="category-tab ${selectedCategory===c.id?'active':''}" data-category="${c.id}" ${categoryStyle(c.color)}>${escapeHtml(c.name)}</button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;renderAll()})}
function cardPreviewHtml(note){if(note.type==='text')return`<p class="card-preview">${escapeHtml(note.content||'内容を入力…')}</p>`;const items=note.items.filter(item=>String(item.text||'').trim());if(!items.length)return'<p class="card-preview">内容を入力…</p>';const visible=items.slice(0,3),hasMore=items.length>3;return`<div class="card-preview card-list-preview">${visible.map((item,index)=>{const marker=note.type==='checklist'?(item.checked?'☑':'□'):'•',suffix=hasMore&&index===visible.length-1?'…':'';return`<div class="card-list-item ${note.type==='checklist'&&item.checked?'completed':''}">${marker} ${escapeHtml(String(item.text).trim())}${suffix}</div>`}).join('')}</div>`}
function renderNotes(){const term=$('searchInput').value.trim().toLowerCase();let shown=notes.filter(n=>{const cat=getCategory(n.categoryId)?.name||'未分類';return(selectedCategory==='all'||n.categoryId===selectedCategory)&&[n.title,n.content,cat,...n.items.map(i=>i.text),...n.urls.map(u=>u.url)].join(' ').toLowerCase().includes(term)});const sort=$('sortSelect').value;shown.sort((a,b)=>{if(a.isPinned!==b.isPinned)return a.isPinned?-1:1;if(sort==='title-asc')return displayTitle(a).localeCompare(displayTitle(b),'ja');const key=sort.startsWith('created')?'createdAt':'updatedAt';return sort.endsWith('asc')?dateMillis(a[key])-dateMillis(b[key]):dateMillis(b[key])-dateMillis(a[key])});$('listTitle').textContent=selectedCategory==='all'?'すべてのメモ':selectedCategory===''?'未分類':getCategory(selectedCategory)?.name||'カテゴリー';$('noteCount').textContent=`${shown.length}件`;$('notesGrid').innerHTML=shown.map(n=>{const c=getCategory(n.categoryId)||{name:'未分類',color:'#6B7280'},color=categoryColor(c.color),progress=n.type==='checklist'?`${n.items.filter(i=>i.checked).length}/${n.items.length}完了`:'',linkInfo=n.urls.length?`🔗 ${n.urls.length}件`:'';return`<article class="note-card" data-id="${n.id}" tabindex="0" role="button"><div class="card-top"><span class="type-icon">${n.type==='text'?'▤':n.type==='bullet'?'☷':'☑'}</span><h3 class="card-title">${escapeHtml(displayTitle(n))}</h3></div>${cardPreviewHtml(n)}<footer class="card-footer"><div class="card-footer-left"><span class="category-pill" style="background:${color};color:${categoryTextColor(color)}">${escapeHtml(c.name)}</span><span>更新 ${shortDate(n.updatedAt)}</span>${linkInfo?`<span>${linkInfo}</span>`:''}</div>${progress||n.isPinned?`<div class="card-footer-right">${progress?`<span class="card-progress">${progress}</span>`:''}${n.isPinned?'<span class="card-pin">★</span>':''}</div>`:''}</footer></article>`}).join('');$('emptyState').hidden=shown.length>0;document.querySelectorAll('.note-card').forEach(card=>{const open=()=>openEditor(notes.find(n=>n.id===card.dataset.id));card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function renderLinks(){$('relatedLinks').innerHTML=editingNote.urls.length?editingNote.urls.map(link=>`<a class="link-card" href="${escapeHtml(link.url)}" target="_blank" rel="noopener noreferrer"><span>🌐</span><div><strong>${escapeHtml(link.title||link.domain||link.url)}</strong><small>${escapeHtml(link.domain||link.url)}</small></div><span>↗</span></a>`).join(''):'<p class="form-error">本文内のURLがここに表示されます。</p>'}
function openCategoryManager(){$('categoryError').textContent='';renderCategoryManagement();$('categoryDialog').showModal()}
function bindNewCategoryColorPalette(){const color=$('newCategoryColor'),palette=$('newCategoryColorPalette'),render=()=>{palette.innerHTML=colorChoices(color.value);palette.querySelectorAll('[data-color-choice]').forEach(button=>button.onclick=()=>{color.value=button.dataset.colorChoice;render()})};color.oninput=render;render()}
function renderCategoryManagement(){$('categoryManagementList').innerHTML=categories.map(c=>`<div class="manage-category-row draggable-category-row" data-id="${c.id}"><input type="color" value="${categoryColor(c.color)}"/><input type="text" value="${escapeHtml(c.name)}"/><span class="drag-handle" aria-hidden="true">≡</span><button type="button" data-delete aria-label="${escapeHtml(c.name)}を削除">削除</button><div class="category-color-palette" aria-label="${escapeHtml(c.name)}の色候補">${colorChoices(c.color)}</div></div>`).join('');document.querySelectorAll('.manage-category-row').forEach(row=>{const category=getCategory(row.dataset.id),color=row.querySelector('input[type=color]'),name=row.querySelector('input[type=text]'),del=row.querySelector('[data-delete]'),setColor=value=>{category.color=categoryColor(value);color.value=category.color;saveCategories().then(ok=>ok&&renderCategoryManagement())};color.oninput=()=>setColor(color.value);row.querySelectorAll('[data-color-choice]').forEach(button=>button.onclick=()=>setColor(button.dataset.colorChoice));name.onchange=()=>renameCategory(category,name.value);del.onclick=()=>confirmCategoryDelete(category);bindCategoryDrag(row)});bindNewCategoryColorPalette()}
function categoryDragAllowedTarget(target){return!target.closest('input[type="color"],button')}
function bindCategoryDrag(row){row.addEventListener('pointerdown',event=>{if(event.pointerType!=='mouse'||categoryDragState||!categoryDragAllowedTarget(event.target))return;const state={row,kind:'pointer',pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,started:false,timer:null};categoryDragState=state;startCategoryDrag(state)});row.addEventListener('pointermove',event=>{const state=categoryDragState;if(!state||state.kind!=='pointer'||state.pointerId!==event.pointerId||!state.started)return;event.preventDefault();event.stopPropagation();restoreCategoryDragScroll(state);updateCategoryDragTarget(event.clientX,event.clientY,state)});row.addEventListener('pointerup',event=>{if(categoryDragState?.kind==='pointer'&&categoryDragState.pointerId===event.pointerId)finishCategoryDrag()});row.addEventListener('pointercancel',event=>{if(categoryDragState?.kind==='pointer'&&categoryDragState.pointerId===event.pointerId)cancelCategoryDrag()});row.addEventListener('touchstart',event=>{if(categoryDragState||!categoryDragAllowedTarget(event.target))return;const touch=event.changedTouches[0];if(!touch)return;const state={row,kind:'touch',touchId:touch.identifier,startX:touch.clientX,startY:touch.clientY,started:false,timer:null,scrollY:window.scrollY,dialogScrollTop:$('categoryDialog').querySelector('form')?.scrollTop||0};categoryDragState=state;state.timer=setTimeout(()=>startCategoryDrag(state),450);document.addEventListener('touchmove',handleCategoryTouchMove,{capture:true,passive:false});document.addEventListener('touchend',finishCategoryTouch,{capture:true,passive:false});document.addEventListener('touchcancel',cancelCategoryTouch,{capture:true,passive:false})},{passive:true})}
function startCategoryDrag(state){if(categoryDragState!==state)return;state.started=true;document.activeElement?.blur();state.row.classList.add('dragging');document.body.classList.add('category-drag-active');$('categoryDialog').classList.add('category-drag-active');if(state.kind==='pointer')state.row.setPointerCapture?.(state.pointerId);navigator.vibrate?.(12)}
function restoreCategoryDragScroll(state){if(!state?.started)return;if(window.scrollY!==state.scrollY)window.scrollTo(0,state.scrollY);const form=$('categoryDialog').querySelector('form');if(form&&form.scrollTop!==state.dialogScrollTop)form.scrollTop=state.dialogScrollTop}
function updateCategoryDragTarget(x,y,state){document.querySelectorAll('.draggable-category-row').forEach(row=>row.classList.remove('drop-before','drop-after'));state.targetId='';state.before=false;const target=document.elementFromPoint(x,y)?.closest('.draggable-category-row');if(!target||target===state.row)return;const before=y<target.getBoundingClientRect().top+target.getBoundingClientRect().height/2;target.classList.add(before?'drop-before':'drop-after');state.targetId=target.dataset.id;state.before=before}
function handleCategoryTouchMove(event){const state=categoryDragState;if(!state||state.kind!=='touch')return;const touch=[...event.touches].find(item=>item.identifier===state.touchId);if(!touch)return;if(!state.started){if(Math.hypot(touch.clientX-state.startX,touch.clientY-state.startY)>10)cancelCategoryDrag();return}event.preventDefault();event.stopPropagation();restoreCategoryDragScroll(state);updateCategoryDragTarget(touch.clientX,touch.clientY,state)}
function finishCategoryTouch(event){const state=categoryDragState;if(!state||state.kind!=='touch'||![...event.changedTouches].some(touch=>touch.identifier===state.touchId))return;if(state.started){event.preventDefault();event.stopPropagation()}finishCategoryDrag()}
function cancelCategoryTouch(event){const state=categoryDragState;if(!state||state.kind!=='touch')return;if(state.started){event.preventDefault();event.stopPropagation()}cancelCategoryDrag()}
function finishCategoryDrag(){const state=categoryDragState;if(!state)return;const sourceId=state.row.dataset.id,targetId=state.targetId,before=state.before,started=state.started;cancelCategoryDrag();if(started&&targetId&&targetId!==sourceId)moveDraggedCategory(sourceId,targetId,before)}
function cancelCategoryDrag(){const state=categoryDragState;if(state){clearTimeout(state.timer);if(state.kind==='touch'){document.removeEventListener('touchmove',handleCategoryTouchMove,{capture:true});document.removeEventListener('touchend',finishCategoryTouch,{capture:true});document.removeEventListener('touchcancel',cancelCategoryTouch,{capture:true})}state.row.classList.remove('dragging')}document.querySelectorAll('.draggable-category-row').forEach(row=>row.classList.remove('drop-before','drop-after'));document.body.classList.remove('category-drag-active');$('categoryDialog').classList.remove('category-drag-active');categoryDragState=null}
async function moveDraggedCategory(sourceId,targetId,before){const previous=categories.map(category=>({...category})),next=categories.map(category=>({...category})),sourceIndex=next.findIndex(category=>category.id===sourceId);if(sourceIndex<0)return;const [source]=next.splice(sourceIndex,1);let targetIndex=next.findIndex(category=>category.id===targetId);if(targetIndex<0)return;if(!before)targetIndex++;next.splice(targetIndex,0,source);next.forEach((category,order)=>category.order=order);categories=next;renderCategoryManagement();const saved=await saveCategories(next);if(!saved){categories=previous;renderCategoryManagement()}}
async function saveCategories(next=categories){const ordered=orderedCategories(next).map((category,order)=>({...category,order}));try{await setDoc(refs().settings,{categories:ordered,updatedAt:serverTimestamp()},{merge:true});categories=ordered;renderAll();return true}catch(e){$('categoryError').textContent=`保存失敗: ${e.message}`;return false}}
function renameCategory(category,name){name=name.trim();if(!name||categories.some(c=>c.id!==category.id&&c.name.toLowerCase()===name.toLowerCase())){$('categoryError').textContent='空欄または重複するカテゴリー名は使えません。';renderCategoryManagement();return}const next=categories.map(c=>c.id===category.id?{...c,name}:c);saveCategories(next)}
function addCategory(){const name=$('newCategoryName').value.trim();if(!name||categories.some(c=>c.name.toLowerCase()===name.toLowerCase())){$('categoryError').textContent='空欄または重複するカテゴリー名は追加できません。';return}const next=[...categories,{id:uid(),name,color:$('newCategoryColor').value,order:categories.length}];$('newCategoryName').value='';saveCategories(next).then(ok=>ok&&renderCategoryManagement())}
function confirmCategoryDelete(category){if(!category||category.id===''||category.name==='未分類'){ $('categoryError').textContent='未分類は削除できません。';return }pendingCategoryId=category.id;$('categoryConfirmTitle').textContent=`カテゴリー「${category.name}」を削除しますか？`;$('categoryConfirmDialog').showModal()}
async function deletePendingCategory(){const category=getCategory(pendingCategoryId);if(!category)return;const used=notes.filter(note=>note.categoryId===category.id);try{if(used.length){const batch=writeBatch(db);used.forEach(note=>batch.update(doc(refs().notes,note.id),{categoryId:'',updatedAt:serverTimestamp()}));await batch.commit()}const next=categories.filter(c=>c.id!==category.id);const saved=await saveCategories(next);if(!saved)throw new Error('カテゴリー設定を保存できませんでした');$('categoryConfirmDialog').close();pendingCategoryId='';renderCategoryManagement()}catch(e){$('categoryError').textContent=`削除に失敗しました: ${e.message}`}}
function confirmDelete(){if(!deletingNote&&editingNote)$('confirmDialog').showModal()}
async function deleteCurrentNote(){if(deletingNote||!editingNote)return;deletingNote=true;$('deleteNoteButton').disabled=true;clearTimeout(saveTimer);saveTimer=null;try{if(saveInProgress||requestedRevision>savedRevision){const saved=await requestSave();if(!saved)throw new Error('保存中の変更を完了できませんでした')}const noteId=editingNote?.id;if(noteId)await deleteDoc(doc(refs().notes,noteId));$('confirmDialog').close();$('editorDialog').close();editingNote=null;editorSession='';editRevision=0;savedRevision=0;requestedRevision=0;savePromise=Promise.resolve(true)}catch(e){setStatus(`削除失敗: ${e.message}`);$('saveStatus').textContent='削除できませんでした。内容を確認してもう一度お試しください。'}finally{deletingNote=false;$('deleteNoteButton').disabled=false}}
async function checkLegacy(){let legacy=[];try{legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]')}catch{}const marker=await getDoc(refs().migration);$('migrationPanel').hidden=!(legacy.length&&!marker.exists())}
async function migrateLegacy(){let legacy=[];try{legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]')}catch{}if(!legacy.length)return;const marker=await getDoc(refs().migration);if(marker.exists())return;const existing=new Set(notes.map(n=>n.id));for(const raw of legacy){const note=normalizeNote('',raw);delete note.id;note.urls=extractUrls(note);const data={...noteData(note),createdAt:raw.createdAt||serverTimestamp(),updatedAt:raw.updatedAt||serverTimestamp()};if(raw.id&&!existing.has(raw.id))await setDoc(doc(refs().notes,raw.id),data);else await addDoc(refs().notes,data)}await setDoc(refs().migration,{completedAt:serverTimestamp(),source:LEGACY_KEY,count:legacy.length});$('migrationPanel').hidden=true;setStatus(`${legacy.length}件を移行しました`)}
initialize();
