/* イロイロキロク: Firestoreを正式保存先にする画面ロジック。 */
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { GoogleAuthProvider, getAuth, onAuthStateChanged, signInWithPopup, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getFirestore, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, writeBatch } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const VERSION='2026.07.13-05'; const LEGACY_KEY='orangememo-notes-v1';
const DEFAULT_CATEGORIES=[['app','アプリ','#fff0e8'],['manga','漫画','#fff8d8'],['blog','ブログ','#eaf5ff'],['cooking','料理','#ecf8ed'],['shopping','買い物','#f5edff'],['research','あとで調べる','#e9f7f5']].map(([id,name,color],order)=>({id,name,color,order}));
const $=id=>document.getElementById(id); const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`; const config=window.IROIRO_FIREBASE_CONFIG||{};
let app,auth,db,currentUser=null,notes=[],categories=[],selectedCategory='all',editingNote=null,saveTimer=null,unsubscribeNotes=null,unsubscribeSettings=null,settingsCreatingForUid='',closingEditor=false,deletingNote=false,pendingCategoryId='',pendingType='',editRevision=0,savedRevision=0,requestedRevision=0,saveInProgress=false,savePromise=Promise.resolve(true),editorSession='';
function configured(){return Boolean(config.apiKey&&config.projectId&&config.appId)}
function refs(){return{notes:collection(db,'users',currentUser.uid,'iroiroNotes'),settings:doc(db,'users',currentUser.uid,'iroiroSettings','main'),migration:doc(db,'users',currentUser.uid,'iroiroMigrations','localStorageV1')}}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
/* Timestamp、Date、旧ISO文字列、serverTimestamp反映前のnullを同じ経路で扱う。 */
function toDate(value){if(!value)return null;let date=null;if(value instanceof Date)date=new Date(value);else if(typeof value.toDate==='function')date=value.toDate();else if(typeof value.toMillis==='function')date=new Date(value.toMillis());else if(typeof value==='object'&&typeof value.seconds==='number')date=new Date(value.seconds*1000+(value.nanoseconds||0)/1e6);else if(typeof value==='number'||typeof value==='string')date=new Date(value);return date&&!Number.isNaN(date.getTime())?date:null}
function dateMillis(value,fallback=0){return toDate(value)?.getTime()??fallback}
function formatDate(value){const date=toDate(value);return date?new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(date):'日時不明'}
function shortDate(value){const date=toDate(value);return date?new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric'}).format(date):'日時不明'}
function getCategory(id){return categories.find(c=>c.id===id)}
function displayTitle(n){return n.title.trim()||((n.type==='text'?n.content:n.items.map(i=>i.text).join(' ')).trim().slice(0,48)||'無題のメモ')}
function normalizeNote(id,data={}){return{id,title:String(data.title||''),type:['text','bullet','checklist'].includes(data.type)?data.type:'text',content:String(data.content||''),items:Array.isArray(data.items)?data.items:[],categoryId:String(data.categoryId||''),urls:Array.isArray(data.urls)?data.urls:[],isPinned:Boolean(data.isPinned),createdAt:data.createdAt??null,updatedAt:data.updatedAt??null}}
function createNote(){const now=new Date();return{id:'',title:'',type:'text',content:'',items:[],categoryId:'',urls:[],isPinned:false,createdAt:now,updatedAt:now}}
function hasMeaningfulContent(note){return Boolean(note.title.trim()||note.content.trim()||note.items.some(item=>String(item.text||'').trim())||extractUrls(note).length)}
function setStatus(message){$('syncStatus').textContent=message}
function initialize(){document.body.dataset.appVersion=VERSION;bindEvents();if(!configured()){$('syncStatus').textContent='Firebase設定が未設定です';$('loginButton').disabled=true;renderAll();return}app=initializeApp(config);auth=getAuth(app);db=getFirestore(app);onAuthStateChanged(auth,handleAuth)}
function bindEvents(){
  $('createNoteButton').onclick=()=>currentUser&&openEditor(createNote()); $('loginButton').onclick=()=>signInWithPopup(auth,new GoogleAuthProvider()).catch(e=>setStatus(`ログイン失敗: ${e.message}`)); $('logoutButton').onclick=()=>signOut(auth);
  $('searchInput').oninput=renderNotes;$('sortSelect').onchange=renderNotes;$('noteTitleInput').oninput=()=>{syncEditingNoteFromForm();scheduleSave()};$('noteContentInput').oninput=()=>{syncEditingNoteFromForm();renderLinks();scheduleSave()};$('noteCategorySelect').onchange=()=>{syncEditingNoteFromForm();scheduleSave()};
  $('closeEditorButton').onclick=e=>{e.preventDefault();closeEditor()}; $('editorDialog').addEventListener('cancel',e=>{e.preventDefault();closeEditor()});
  $('pinButton').onclick=()=>{editingNote.isPinned=!editingNote.isPinned;updateEditor();scheduleSave()}; $('deleteNoteButton').onclick=confirmDelete;$('confirmDeleteButton').onclick=e=>{e.preventDefault();deleteCurrentNote()};
  $('addItemButton').onclick=()=>{editingNote.items.push({id:uid(),text:'',checked:false,order:editingNote.items.length});renderItems();scheduleSave()}; $('typeSwitcher').onclick=e=>{const type=e.target.dataset.type;if(type)requestTypeChange(type)};
  ['manageCategoriesButton','mobileManageCategoriesButton'].forEach(id=>$(id).onclick=openCategoryManager);$('addCategoryButton').onclick=addCategory;$('confirmCategoryDeleteButton').onclick=e=>{e.preventDefault();deletePendingCategory()}; $('confirmTypeChangeButton').onclick=e=>{e.preventDefault();applyTypeChange(pendingType);$('typeConfirmDialog').close()};
  $('migrateLocalButton').onclick=migrateLegacy;
}
function clearRealtimeListeners(){if(unsubscribeNotes){unsubscribeNotes();unsubscribeNotes=null}if(unsubscribeSettings){unsubscribeSettings();unsubscribeSettings=null}}
async function handleAuth(user){clearRealtimeListeners();settingsCreatingForUid='';currentUser=user;if(!user){notes=[];categories=[];$('loginButton').hidden=false;$('logoutButton').hidden=true;setStatus(configured()?'ログインすると同期できます':'Firebase設定が未設定です');renderAll();return}const activeUid=user.uid;$('loginButton').hidden=true;$('logoutButton').hidden=false;setStatus('同期中…');const activeSettings=doc(db,'users',activeUid,'iroiroSettings','main');const activeNotes=collection(db,'users',activeUid,'iroiroNotes');unsubscribeSettings=onSnapshot(activeSettings,snap=>{if(currentUser?.uid!==activeUid)return;if(snap.exists()&&Array.isArray(snap.data().categories)){applyRemoteCategories(snap.data().categories);return}if(settingsCreatingForUid!==activeUid){settingsCreatingForUid=activeUid;setDoc(activeSettings,{categories:structuredClone(DEFAULT_CATEGORIES),updatedAt:serverTimestamp()}).catch(e=>setStatus(`カテゴリー初期化失敗: ${e.message}`)).finally(()=>{if(settingsCreatingForUid===activeUid)settingsCreatingForUid=''})}},err=>setStatus(`カテゴリー同期失敗: ${err.message}`));unsubscribeNotes=onSnapshot(query(activeNotes,orderBy('updatedAt','desc')),snap=>{if(currentUser?.uid!==activeUid)return;notes=snap.docs.map(x=>normalizeNote(x.id,x.data()));setStatus('同期済み');renderAll()},err=>setStatus(`同期失敗: ${err.message}`));try{await checkLegacy()}catch(e){setStatus(`移行状態の確認失敗: ${e.message}`)}}
function applyRemoteCategories(nextCategories){categories=nextCategories;renderAll();refreshEditorCategoryOptions()}
function refreshEditorCategoryOptions(){if(!editingNote||!$('editorDialog').open)return;const select=$('noteCategorySelect');const current=editingNote.categoryId;select.innerHTML=`<option value="">未分類</option>${categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}`;if(current===''||categories.some(c=>c.id===current)){select.value=current;return}editingNote.categoryId='';select.value='';scheduleSave()}
function openEditor(note){editingNote=structuredClone(note);editorSession=uid();editRevision=0;savedRevision=0;requestedRevision=0;saveInProgress=false;savePromise=Promise.resolve(true);updateEditor();$('editorDialog').showModal();setTimeout(()=>$('noteTitleInput').focus(),40)}
function syncEditingNoteFromForm(){if(!editingNote)return;editingNote.title=$('noteTitleInput').value;editingNote.content=$('noteContentInput').value;editingNote.categoryId=$('noteCategorySelect').value;editingNote.urls=extractUrls(editingNote)}
function updateEditor(){const n=editingNote;$('noteTitleInput').value=n.title;$('noteContentInput').value=n.content;$('noteCategorySelect').innerHTML=`<option value="">未分類</option>${categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}`;$('noteCategorySelect').value=n.categoryId;$('textEditor').hidden=n.type!=='text';$('itemsEditor').hidden=n.type==='text';document.querySelectorAll('#typeSwitcher button').forEach(b=>b.classList.toggle('active',b.dataset.type===n.type));$('pinButton').classList.toggle('active',n.isPinned);$('pinButton').textContent=`${n.isPinned?'★':'♧'} ピン留め`;$('createdAt').textContent=formatDate(n.createdAt);$('updatedAt').textContent=formatDate(n.updatedAt);renderItems();renderLinks();$('saveStatus').textContent='保存済み'}
function refreshRelatedLinks(){if(!editingNote)return;editingNote.urls=extractUrls(editingNote);renderLinks()}
function renderItems(){$('itemsList').innerHTML=editingNote.items.map((item,index)=>`<div class="item-row ${item.checked?'checked':''}"><input type="${editingNote.type==='checklist'?'checkbox':'button'}" ${editingNote.type==='checklist'&&item.checked?'checked':''} ${editingNote.type==='bullet'?'value="•" tabindex="-1"':''} data-check="${index}"/><input type="text" value="${escapeHtml(item.text)}" placeholder="項目を入力" data-item="${index}"/><button type="button" class="remove-item" data-remove="${index}" aria-label="項目を削除">×</button></div>`).join('');document.querySelectorAll('[data-item]').forEach(el=>{el.oninput=e=>{editingNote.items[e.target.dataset.item].text=e.target.value;refreshRelatedLinks();scheduleSave()};el.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const at=+e.target.dataset.item+1;editingNote.items.splice(at,0,{id:uid(),text:'',checked:false,order:at});editingNote.items.forEach((x,i)=>x.order=i);renderItems();refreshRelatedLinks();scheduleSave();document.querySelector(`[data-item="${at}"]`)?.focus()}}});document.querySelectorAll('[data-check]').forEach(el=>el.onchange=e=>{if(editingNote.type==='checklist'){editingNote.items[e.target.dataset.check].checked=e.target.checked;renderItems();refreshRelatedLinks();scheduleSave()}});document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=e=>{editingNote.items.splice(+e.currentTarget.dataset.remove,1);editingNote.items.forEach((x,i)=>x.order=i);renderItems();refreshRelatedLinks();scheduleSave()})}
function trimUrlEnding(value){return value.replace(/[。、，．！？）】」』〉》;:,.]+$/u,'')}
function extractUrls(note){const text=note.type==='text'?note.content:note.items.map(i=>i.text).join('\n');const found=text.match(/https?:\/\/[^\s<>"']+/g)||[];const links=[];for(const raw of found){const url=trimUrlEnding(raw);try{const parsed=new URL(url);if((parsed.protocol==='http:'||parsed.protocol==='https:')&&!links.some(link=>link.url===parsed.href))links.push({url:parsed.href,title:'',domain:parsed.hostname.replace(/^www\./,'')})}catch{}}return links}
function requestTypeChange(type){if(!editingNote||deletingNote||type===editingNote.type)return;syncEditingNoteFromForm();if(hasMeaningfulContent(editingNote)){pendingType=type;$('typeConfirmDialog').showModal();return}applyTypeChange(type)}
function applyTypeChange(type){if(!type)return;editingNote.type=type;if(type!=='text'&&!editingNote.items.length)editingNote.items=[{id:uid(),text:'',checked:false,order:0}];pendingType='';updateEditor();scheduleSave()}
function scheduleSave(){if(deletingNote||!editingNote)return;editRevision++;$('saveStatus').textContent='保存中…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>requestSave(),550)}
function noteData(note){return{title:note.title, type:note.type, content:note.content, items:note.items, categoryId:note.categoryId, urls:note.urls, isPinned:note.isPinned}}
function captureSaveSnapshot(){syncEditingNoteFromForm();return{note:structuredClone(editingNote),session:editorSession}}
function requestSave(){requestedRevision=Math.max(requestedRevision,editRevision);if(saveInProgress)return savePromise;if(requestedRevision<=savedRevision)return Promise.resolve(true);savePromise=drainSaveQueue();return savePromise}
async function drainSaveQueue(){saveInProgress=true;try{while(savedRevision<requestedRevision){const revision=requestedRevision;const snapshot=captureSaveSnapshot();const result=await persistSnapshot(snapshot);if(!result.ok)return false;savedRevision=revision}return true}finally{saveInProgress=false}}
async function persistSnapshot(snapshot){if(!currentUser||!snapshot.note)return{ok:false};const isNew=!snapshot.note.id;if(isNew&&!hasMeaningfulContent(snapshot.note)){$('saveStatus').textContent='未保存（空のメモ）';return{ok:true,skipped:true}}$('saveStatus').textContent='保存中…';try{if(isNew){const created=await addDoc(refs().notes,{...noteData(snapshot.note),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});if(editingNote&&editorSession===snapshot.session&&!editingNote.id)editingNote.id=created.id}else await updateDoc(doc(refs().notes,snapshot.note.id),{...noteData(snapshot.note),updatedAt:serverTimestamp()});$('saveStatus').textContent='保存済み';if(editingNote&&editorSession===snapshot.session){editingNote.urls=structuredClone(snapshot.note.urls);renderLinks()}return{ok:true}}catch(e){$('saveStatus').textContent='保存できませんでした';setStatus(`保存失敗: ${e.message}`);return{ok:false,error:e}}}
async function closeEditor(){if(closingEditor||!editingNote)return;closingEditor=true;clearTimeout(saveTimer);requestedRevision=Math.max(requestedRevision,editRevision);const result=requestedRevision>savedRevision||saveInProgress?await requestSave():true;if(result){$('editorDialog').close();editingNote=null;editorSession=''}else $('saveStatus').textContent='保存できませんでした。内容を確認してもう一度お試しください。';closingEditor=false}
function renderAll(){renderCategories();renderNotes()}
function renderCategories(){const list=[{id:'all',name:'すべて',color:'#fff'},...categories,{id:'',name:'未分類',color:'#f1efed'}];const nav=c=>`<button class="category-nav-item ${selectedCategory===c.id?'active':''}" data-category="${c.id}"><span class="category-dot" style="background:${c.color}"></span>${escapeHtml(c.name)}</button>`;$('sidebarCategories').innerHTML=list.map(nav).join('');$('categoryTabs').innerHTML=list.map(c=>`<button class="${selectedCategory===c.id?'active':''}" data-category="${c.id}">${escapeHtml(c.name)}</button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;renderAll()})}
function renderNotes(){const term=$('searchInput').value.trim().toLowerCase();let shown=notes.filter(n=>{const cat=getCategory(n.categoryId)?.name||'未分類';return(selectedCategory==='all'||n.categoryId===selectedCategory)&&[n.title,n.content,cat,...n.items.map(i=>i.text),...n.urls.map(u=>u.url)].join(' ').toLowerCase().includes(term)});const sort=$('sortSelect').value;shown.sort((a,b)=>{if(a.isPinned!==b.isPinned)return a.isPinned?-1:1;if(sort==='title-asc')return displayTitle(a).localeCompare(displayTitle(b),'ja');const key=sort.startsWith('created')?'createdAt':'updatedAt';return sort.endsWith('asc')?dateMillis(a[key])-dateMillis(b[key]):dateMillis(b[key])-dateMillis(a[key])});$('listTitle').textContent=selectedCategory==='all'?'すべてのメモ':selectedCategory===''?'未分類':getCategory(selectedCategory)?.name||'カテゴリー';$('noteCount').textContent=`${shown.length}件`;$('notesGrid').innerHTML=shown.map(n=>{const c=getCategory(n.categoryId)||{name:'未分類',color:'#f1efed'},preview=n.type==='text'?n.content:n.items.map(i=>i.text).filter(Boolean).join(' ・ '),progress=n.type==='checklist'?`${n.items.filter(i=>i.checked).length}/${n.items.length}完了`:'',linkInfo=n.urls.length?`🔗 ${n.urls.length}件`:'';return`<article class="note-card" data-id="${n.id}" tabindex="0" role="button"><div class="card-top"><span class="type-icon">${n.type==='text'?'▤':n.type==='bullet'?'☷':'☑'}</span><h3 class="card-title">${escapeHtml(displayTitle(n))}</h3></div><p class="card-preview">${escapeHtml(preview||'内容を入力…')}</p><footer class="card-footer"><span class="category-pill" style="background:${c.color}">${escapeHtml(c.name)}</span><span>更新 ${shortDate(n.updatedAt)}</span>${progress?`<span>${progress}</span>`:''}${linkInfo?`<span>${linkInfo}</span>`:''}${n.isPinned?'<span class="card-pin">★</span>':''}</footer></article>`}).join('');$('emptyState').hidden=shown.length>0;document.querySelectorAll('.note-card').forEach(card=>{const open=()=>openEditor(notes.find(n=>n.id===card.dataset.id));card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function renderLinks(){$('relatedLinks').innerHTML=editingNote.urls.length?editingNote.urls.map(link=>`<a class="link-card" href="${escapeHtml(link.url)}" target="_blank" rel="noopener noreferrer"><span>🌐</span><div><strong>${escapeHtml(link.title||link.domain||link.url)}</strong><small>${escapeHtml(link.domain||link.url)}</small></div><span>↗</span></a>`).join(''):'<p class="form-error">本文内のURLがここに表示されます。</p>'}
function openCategoryManager(){$('categoryError').textContent='';renderCategoryManagement();$('categoryDialog').showModal()}
function renderCategoryManagement(){$('categoryManagementList').innerHTML=categories.map(c=>`<div class="manage-category-row" data-id="${c.id}"><input type="color" value="${c.color}"/><input type="text" value="${escapeHtml(c.name)}"/><button type="button">削除</button></div>`).join('');document.querySelectorAll('.manage-category-row').forEach(row=>{const category=getCategory(row.dataset.id),[color,name,del]=row.querySelectorAll('input,button');color.oninput=()=>{category.color=color.value;saveCategories()};name.onchange=()=>renameCategory(category,name.value);del.onclick=()=>confirmCategoryDelete(category)})}
async function saveCategories(next=categories){try{await setDoc(refs().settings,{categories:next,updatedAt:serverTimestamp()},{merge:true});categories=next;renderAll();return true}catch(e){$('categoryError').textContent=`保存失敗: ${e.message}`;return false}}
function renameCategory(category,name){name=name.trim();if(!name||categories.some(c=>c.id!==category.id&&c.name.toLowerCase()===name.toLowerCase())){$('categoryError').textContent='空欄または重複するカテゴリー名は使えません。';renderCategoryManagement();return}const next=categories.map(c=>c.id===category.id?{...c,name}:c);saveCategories(next)}
function addCategory(){const name=$('newCategoryName').value.trim();if(!name||categories.some(c=>c.name.toLowerCase()===name.toLowerCase())){$('categoryError').textContent='空欄または重複するカテゴリー名は追加できません。';return}const next=[...categories,{id:uid(),name,color:$('newCategoryColor').value,order:categories.length}];$('newCategoryName').value='';saveCategories(next).then(ok=>ok&&renderCategoryManagement())}
function confirmCategoryDelete(category){if(!category||category.id===''||category.name==='未分類'){ $('categoryError').textContent='未分類は削除できません。';return }pendingCategoryId=category.id;$('categoryConfirmTitle').textContent=`カテゴリー「${category.name}」を削除しますか？`;$('categoryConfirmDialog').showModal()}
async function deletePendingCategory(){const category=getCategory(pendingCategoryId);if(!category)return;const used=notes.filter(note=>note.categoryId===category.id);try{if(used.length){const batch=writeBatch(db);used.forEach(note=>batch.update(doc(refs().notes,note.id),{categoryId:'',updatedAt:serverTimestamp()}));await batch.commit()}const next=categories.filter(c=>c.id!==category.id);const saved=await saveCategories(next);if(!saved)throw new Error('カテゴリー設定を保存できませんでした');$('categoryConfirmDialog').close();pendingCategoryId='';renderCategoryManagement()}catch(e){$('categoryError').textContent=`削除に失敗しました: ${e.message}`}}
function confirmDelete(){if(!deletingNote&&editingNote)$('confirmDialog').showModal()}
async function deleteCurrentNote(){if(deletingNote||!editingNote)return;deletingNote=true;$('deleteNoteButton').disabled=true;clearTimeout(saveTimer);saveTimer=null;try{if(saveInProgress||requestedRevision>savedRevision){const saved=await requestSave();if(!saved)throw new Error('保存中の変更を完了できませんでした')}const noteId=editingNote?.id;if(noteId)await deleteDoc(doc(refs().notes,noteId));$('confirmDialog').close();$('editorDialog').close();editingNote=null;editorSession='';editRevision=0;savedRevision=0;requestedRevision=0;savePromise=Promise.resolve(true)}catch(e){setStatus(`削除失敗: ${e.message}`);$('saveStatus').textContent='削除できませんでした。内容を確認してもう一度お試しください。'}finally{deletingNote=false;$('deleteNoteButton').disabled=false}}
async function checkLegacy(){let legacy=[];try{legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]')}catch{}const marker=await getDoc(refs().migration);$('migrationPanel').hidden=!(legacy.length&&!marker.exists())}
async function migrateLegacy(){let legacy=[];try{legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]')}catch{}if(!legacy.length)return;const marker=await getDoc(refs().migration);if(marker.exists())return;const existing=new Set(notes.map(n=>n.id));for(const raw of legacy){const note=normalizeNote('',raw);delete note.id;note.urls=extractUrls(note);const data={...noteData(note),createdAt:raw.createdAt||serverTimestamp(),updatedAt:raw.updatedAt||serverTimestamp()};if(raw.id&&!existing.has(raw.id))await setDoc(doc(refs().notes,raw.id),data);else await addDoc(refs().notes,data)}await setDoc(refs().migration,{completedAt:serverTimestamp(),source:LEGACY_KEY,count:legacy.length});$('migrationPanel').hidden=true;setStatus(`${legacy.length}件を移行しました`)}
initialize();
